### ISSUE TITLE
[5.0 Opinion] Opening first tree (element provider) on every perspective is annoying/confusing in many cases

### ISSUE THREAD

**Issue by slacto** [Orckestra/C1-CMS-Foundation#101]

**Comment by wwwysocki** [comment]
Could you please elaborate?

What should I do to reproduce an issue (issues)?
Or what could be improved?

Thank you

**Comment by slacto** [comment]
When you open the console the Websites node is open. When you go to other perspectives, the first node is open. I rarely use Page Types so it should not be open. I think default open/closed should be something I set in Composite.config like:
<add providerName="PageTemplateElementProvider" name="PageTemplateElementProvider" type="Composite.Plugins.Elements.ElementProviders.VirtualElementProvider.AttachProviderVirtualElement, Composite" open=”false” />

**Comment by slacto** [comment]
add providerName="PageTemplateElementProvider" name="PageTemplateElementProvider" type="Composite.Plugins.Elements.ElementProviders.VirtualElementProvider.AttachProviderVirtualElement, Composite" open=”false”

**Comment by wwwysocki** [comment]
Clear. Thank you.

Just for the reference: below is the current [default] behavior described - what node gets selected and expanded in each perspective

* **Content**: "Websites" / "Venus Starter Site" (or the home page of the [first] website below "Websites")
* **Media**: "Media Archive"
* **Data**: "Global Data Types"
* **Layout**: "Page Types"
* **Functions**: "Razor Functions"
* **System**: "Packages" / "Available Packages"

**Comment by mawtex** [comment]
Making this a configurable option is probably not gonna happen (more important stuff to do first), but showing Templates on the Layout Perspective would be a lot more useful than page types. This is a pretty easy fix I'll commit. I'll then close this.

**Comment by burningice2866** [comment]
... and auto-opening packages on the System tab is quite annoying as well :)

I know i can just change the order of elementproviders in composite.config, but i agree with @slacto - its still annoying :)
