### ISSUE TITLE
Html.C1().Function("...") clears the existing FunctionContext

### ISSUE THREAD

**Issue by burningice2866** [Orckestra/C1-CMS-Foundation#191]
Calling `Html.C1().Function(...)` without passing a `FunctionContext` clears the existing instead of passing it as expected

https://github.com/Orckestra/C1-CMS/blob/master/Composite/AspNet/Razor/C1HtmlHelper.cs#L434

Clearing the context and start a new should be an explicit decision, not implicit as now.

**Comment by kasravi** [comment]
Can you describe a test case? or may be a pull request?

**Comment by burningice2866** [comment]
@kasravi repo:

1. Download the [following gist](https://gist.github.com/burningice2866/600e0d42c69fc01d5b7ef6de0750b42b) into App_Data/Razor/Issue191
2. Insert the function "Issue191.Parent" unto a page

Expected: All lines should state that **It works as it should**
Actual: First line says **It didn't work**

When working on a PR it became clear that the `C1HtmlHelper` returned from calling `Html.C1()` doesn't have access to the current page in question, and the fix is therefor to add an overload to `CompositeC1WebPage.Function(...)` to allow passing a `FunctionContextContainer` instance, something it doesn't allow now and you therefor end up in a weird mix of calling either `Function(...)` or `Html.C1().Function(...)`.

It's also my feeling that the usage of `Html.C1().Function(...)` without passing a `FunctionContextContainer` should be depricated in favor of simply calling `Function(...)`,, since calling `Html.C1().Function(...)` either with or without an `FunctionContextContainer` behaves differently. I've therefor added an Obsolete-property to the methods in question on the `C1HtmlHelper` class.

PS. The whole problem originates [here](https://github.com/ASP-NET-MVC/aspnetwebstack/blob/master/src/System.Web.WebPages/WebPage.cs#L97), where an instance of this (the current `WebPage`) isn't passed to the `HtmlHelper` the same way as [Mvc does it](https://github.com/ASP-NET-MVC/aspnetwebstack/blob/master/src/System.Web.Mvc/WebViewPage.cs#L32).

A long term fix is to let `CompositeC1WebPage` inherit from `WebPageBase` instead of `WebPage`, which allows for a custom implementation of the `HtmlHelper` property.

**Comment by burningice2866** [comment]
@kasravi any news?

**Comment by burningice2866** [comment]
@kasravi any news?

**Comment by burningice2866** [comment]
@kasravi any news?

**Comment by napernik** [comment]
Merged to dev https://github.com/Orckestra/C1-CMS-Foundation/commit/dcbc25f7cc120179751d9d50bedbe959a49c7d67
