### ISSUE TITLE
The file doesn't always appear in the tree when uploaded

### ISSUE THREAD

**Issue by wwwysocki** [Orckestra/C1-CMS-Foundation#192]
**Note**: The following repro scenario is not 100%. The issue occurs occasionally.

A comment for a possible fix:

Make sure to send tree refresh messages and element focus messages to the client **AFTER** the transaction has completed, as the client may pick up those messages and do the refresh before the data and file is ready.

**Prepare**:
1. Create a global data type.
2. Add a field of the type: Data Reference / C1 Image.

**Repro**:
1. Add a data item of the type above.
2. Click the field to invoke the "Select Image" window.
3. Select a media folder in the tree and click "Upload File"
4. Browse for, and select an image file.
5. Click "Finish" in the "Add New Media File" window.

**Expected**: The file appears in the tree and gets selected and previewed in the "Select Image" window.
**Actual**: [occasionally] The file doesn't appear in the tree and doesn't get selected/previewed.

You may need to repeat the steps multiple times to get it reproduced.

At least one of the errors causing this is that the image preview fails because the image is not yet ‘on the disk’ when the client refreshes the tree and selects the newly uploaded image (see the error screen below). Manually refreshing and retrying will fix things (so data ends up at the right places).

There is an JS error which may help identify the issue:

CSSUtil.js:85 GET http://_{somewebsite}_/media(f23ee8a4-fb2d-4899-9f0a-d8659282fcbc)?mw=300&mh=170&timestamp=1724702986 500 (Internal Server Error) (~/Composite/scripts/source/top/css/CSSUtil.js)

And this is what happens if you click on that image:

![error-when-uploading-images](https://cloud.githubusercontent.com/assets/14821915/16299514/7195cfa6-3943-11e6-9c21-7ab420905185.png)

**Comment by Luo-Liang** [comment]
Hey! Just want to follow up, as the following related problem can still happen:

Admin1 uploads an image, and before it is truly done, the file is reflected in the tree.
Admin2 can move or delete it, while admin1's operation is still being processed.
Admin1's operation finally finishes, it will trigger the FileNotFoundException.
