### ISSUE TITLE
C1 5 - Url configuration - wrong markup path

### ISSUE THREAD

**Issue by Aben19** [Orckestra/C1-CMS-Foundation#198]
we receive a bunch off errors using the files posted on [https://github.com/Orckestra/C1-CMS/commit/31415aa5231397312e226320f994b9683b87da73](url)

`The Custom-Markup-Path '~/Composite/content/forms/Administrative/UrlConfiguration.xml' is wrong formated. Use ~ / Dir1/Dir2/File.xml at /ElementStructure/ElementRoot/Children/DataElements/Actions/EditDataAction in UrlConfiguration.xml
TreeFacade Error

The File 'F:\wwwroot\AGE\Composite\content\forms\Administrative\UrlConfiguration.xml' does not exist at /ElementStructure/ElementRoot/Children/DataElements/Actions/EditDataAction
in F:\wwwroot\AGE\App_Data\Composite\TreeDefinitions\UrlConfiguration.xml
TreeFacade Error

The Custom-Markup-Path '~/Composite/content/forms/Administrative/Hostnames.xml' ist falsch formatiert. Use ~ / Dir1/Dir2/File.xml at /ElementStructure/ElementRoot/Children/DataElements/Children/Element/Actions/AddDataAction in F:\wwwroot\AGE\App_Data\Composite\TreeDefinitions\UrlConfiguration.xml
TreeFacade Error`

does anybody has a solution for this....

**Comment by burningice2866** [comment]
@Aben19 I'm not sure i follow what files specifically you refer to. The commit in your link is REMOVING files from the source, not adding or modifying files.

**Comment by Aben19** [comment]
@burningice2866 I refer to the following commit by napernik "Moving url configuration out of core product", the files posted there are not working in C1 v5, there's an issue with the Custom-Markup-Path, see error messages above. Does anybody have a solution for this problem?

**Comment by burningice2866** [comment]
@Aben19 No files are posted in that commit, files are removed.
