### ISSUE TITLE
CSS file can not compile

### ISSUE THREAD

**Issue by sampaghosh** [Orckestra/C1-CMS-Foundation#264]
I have downloaded the CMS-Foundation-dev from your git hub and tried to run this. But getting the same error "CSS file can not compile. Followed the steps but still getting the error.

The error is still there.

![cms-error](https://cloud.githubusercontent.com/assets/22800203/19497015/094404ec-953f-11e6-8902-7b23284e19ac.png)

Please can I have some solution.

**Comment by mawtex** [comment]
A fast solution is to grab a pre-compiled release - see https://github.com/Orckestra/CMS-Foundation/releases - unless you plan to run your own fork of Orckestra CMS (which may complicate using our support / upgrade services) I highly recommend you use a public release.

You can also run the grunt script via Visual Studio 2015 - open the "Task Runner Explorer" in VS and navigate down Gruntfile.js / Alias Tasks / build - right click the "build" node and choose "Run"
