### ISSUE TITLE
Serialized EntityToken-s are not readable and occupy too much space

### ISSUE THREAD

**Issue by napernik** [Orckestra/C1-CMS-Foundation#269]
EntityToken-s are used to uniquely identify elements in the console trees. 
At the moment the serialized values are unnecessary  verbose and hard to read/costly to store, particullary, when they contain references to the parent entity tokens and the content gets encoded multiple times.

Proposed solution: to use json-like format, to eliminate multiple levels of encoding and reduce memory usage when processing/caching entity tokens. Some kind of type aliases could also be useful.

**Example 1**:  An entity token for a perspective.

Before 380 (bytes):

_entityTokenType='Composite.Plugins.Elements.ElementProviders.VirtualElementProvider.VirtualElementProviderEntityToken,Composite'entityToken='_EntityToken_Type_=\'Composite\.Plugins\.Elements\.ElementProviders\.VirtualElementProvider\.VirtualElementProviderEntityToken,Composite\'_EntityToken_Source_=\'VirtualElementProvider\'_EntityToken_Id_=\'MediaPerspective\''

Variant 1 (180 bytes)

_{type:'Composite.Plugins.Elements.ElementProviders.VirtualElementProvider.VirtualElementProviderEntityToken,Composite',Id:'MediaPerspective'}_

Variant 2 (52 bytes)

_{type:'VirtualElementProvider',Id:'MediaPerspective'}_

**Example 2**: a page data folder entity token (804 bytes)

_entityTokenType='Composite.C1Console.Trees.TreeSimpleElementEntityToken,Composite'entityToken='_EntityToken_Type_=\'entityTokenType=\\'Composite\\\.Data\\\.DataEntityToken,Composite\\'entityToken=\\'_dataId_=\\\\'Id=\\\\\\\\'059375ee-030f-4891-8af8-7bee530e5985\\\\\\\\',\\\\\\\\ VersionId=\\\\\\\\'059375ee-030f-4891-8af8-7bee530e5985\\\\\\\\'\\\\'_dataIdType_=\\\\'CompositeGenerated\\\\\\\.DynamicSqlDataProvider\\\\\\\.Composite_Data_Types_IPageDataId\\\\'_interfaceType_=\\\\'Composite\\\\\\\.Data\\\\\\\.Types\\\\\\\.IPage,Composite\\\\'_dataScope_=\\\\'administrated\\\\'_localeScope_=\\\\'en-US\\\\'\\'\'_EntityToken_Source_=\'Navigation\.xml\'_EntityToken_Id_=\'NavElem\''_

Variant 1:

_{type:'Composite.C1Console.Trees.TreeSimpleElementEntityToken,Composite',
entityToken:{
 type:'Composite.Data.DataEntityToken,Composite'
 dataId:{Id:'059375ee-030f-4891-8af8-7bee530e5985', VersionId='059375ee-030f-4891-8af8-7bee530e5985'},
 dataIdType:'CompositeGenerated.DynamicSqlDataProvider.Composite_Data_Types_IPageDataId',
 interfaceType:'Composite.Data.Types.IPage,Composite'
 dataScope: 'administrated'
 localeScope: 'en-US'},
source_:'Navigation.xml',
Id:'NavElem'}_

Variant 2 (384 bytes):

_{type:'TreeSimpleElement',
entityToken:{
 type:'Data'
 dataId:{Id:'059375ee-030f-4891-8af8-7bee530e5985', VersionId:'059375ee-030f-4891-8af8-7bee530e5985'},
 dataIdType:'CompositeGenerated.DynamicSqlDataProvider.Composite_Data_Types_IPageDataId',
 interfaceType:'Composite.Data.Types.IPage,Composite'
 dataScope: 'administrated'
 localeScope: 'en-US'},
source_:'Navigation.xml',
Id:'NavElem'}_

**Comment by burningice2866** [comment]
I suppose this one can be closed?

**Comment by napernik** [comment]
Yes, implemented
