### ISSUE TITLE
Questions regarding CMS

### ISSUE THREAD

**Issue by sampaghosh** [Orckestra/C1-CMS-Foundation#278]
Hi,
I have few questions.
1. What is the difference between mercury and Master page on CMS ?
2. What is the difference between mercury and Master page on CMS for asp.net development point of view?
3. Can you add mercury look and feel to the Master page?

Can anybody please let me know?

**Comment by mawtex** [comment]
"Master Page" typically describe asp.net master pages, a templating technology used for ASPX pages and similar (onld Web Forms asp.net tech). In C1 you can use this as a basis for your templates as an alternative to Razor based templates.

"Mercury" is the name of one of our starter sites  - a bundle of templates, content, css, images etc. This particular starter site uses Razor based templates (so not Master Pages).

From a dev point of view the question is more "what is the difference between Master Pages and Razor?" and the answer is that Master Pages (Web Forms in general) is pretty old school and probably you'd only use master pages if you are somewhat stuck in the past or you have a Web Forms based solution you with you migrate to C1 without much modification. Razor is a lot simpler in general and as a syntax chances are you'll instantly love it.

> Can you add mercury look and feel to the Master page?

You can get the same look and feel regardless of technology - you can install the Marcury starter site and then make Master Page versions of the Layout Templates - using the same html structure and css etc. includes you should get the same look and feel.
