### ISSUE TITLE
[Chrome] [VisualEditor] pasting 100+ lines is really slow

### ISSUE THREAD

**Issue by napernik** [Orckestra/C1-CMS-Foundation#303]
Repro:
1) Open a C1 page for editing in Chrome
2) Go to https://www.rottentomatoes.com/m/batman_begins/quotes/ and copy the text lines
3) Past the lines into a Notepad, and copy from Notepad, so there's no styling copied.
4) Try to paste the lines into the opened C1 page
Expected: the text line as inserted
Actual: browser window becomes unresponsive

While the scenario works correctly in Firefox, in Chrome after 100+ lines delay is visible and it grows not proportionally to the amount of lines added.

**Comment by burningice2866** [comment]
+1 for Batman quotes 😆

**Comment by wwwysocki** [comment]
Not reproducible on > v.6.5

**Comment by wwwysocki** [comment]
No longer reproducible on v.6.5 or later
