### ISSUE TITLE
Inherited protocol (double slash) instead of hardcoded "http" in DefaultPageUrlProvider

### ISSUE THREAD

**Issue by sfedor** [Orckestra/C1-CMS-Foundation#330]
We use only the HTTPS protocol on our websites. Even though [DefaultPageUrlProvider](https://github.com/Orckestra/CMS-Foundation/blob/0fc800c81e33414cc25a66b6c50da6bba0c1ec4f/Composite/Plugins/Routing/Pages/DefaultPageUrlProvider.cs#L783) generates HTTP based URLs when we link an URL on another domain name: 

**CMS-Foundation/Composite/Plugins/Routing/Pages/DefaultPageUrlProvider.cs**

`result.Append("http://").Append(hostnameBinding.Hostname);`

We have to add the HTTP to HTTPS redirection. However, it was nice if we could generate URLs with an inherited protocol: 

`result.Append("//").Append(hostnameBinding.Hostname);`

**Comment by napernik** [comment]
We have added **EnforceHttps** property to hostname bindings that would define which protocol to use, as creating a "//" link would have a different problem, if only one site of many has HTTPS binding (and some instances do have 20+ sites), making an HTTPS->HTTP redirects for the other domains would require having certificates for those domains.
