### ISSUE TITLE
Issue applying different Permissions to Media folders.

### ISSUE THREAD

**Issue by Rogn** [Orckestra/C1-CMS-Foundation#360]
Hi,
I have just downloaded the latest version of Orckestra CMS (5.5.6162.32841), and I am having an issue applying permissions to media folders in the media archive. 
It seems like permissions applied to any folder, will always reflect to all other media folders available.

I have the following basic setup:
![image](https://cloud.githubusercontent.com/assets/3670768/22175416/9adf6fa4-dff4-11e6-992b-40dd3a4311b5.png)

And when I apply some permissions to SubFolder1, the permissions I e.g. had applied to Folder2 are overwritten, with the permissions I applied to SubFolder1.

**Comment by mawtex** [comment]
I'm unable to repro this. If you close all open "Permissions" tabs and reopen them for the two folders, you should see the original permissions you set - your experience could stem from you expecting the open tabs reflecting a selection change in the tree view (which they don't).

I can see the UX being a bit bad here - if you have Permissions open for two folders, there is nothing on the tab that indicate the source element they relate to.

**Comment by Konc** [comment]
I too am having issues with permissions in the media archive. 
![media1](https://cloud.githubusercontent.com/assets/2979149/22922548/82a2cf1e-f29e-11e6-8653-bf9cf79ffc73.png)

Any permissions I set for a user group on the folder Media Archive / Images / News _also_ get set on all the folders under Media Archive (i.e. Docs, Media, Sample Images) and all subfolders.

If I then choose to further change permissions for the user group on a different folder, e.g. Media Archive / Images / Covers, that _also_ gets set on all the other folders under Media Archive.

It seems like there's only one tier of permissions, on or off for everything.

Between all permission changes, I closed all open "Permissions" tabs _and_ reloaded the entire C1 console.

**Comment by Rogn** [comment]
I retested this in the latest 6.0 build, and there everything works as expected.

**Comment by Konc** [comment]
Glad to hear it, I'm looking forward to when we can update our Windows server. However we're stuck on version 5.6 for a while longer, and I would really like to see a fix for this.

**Comment by napernik** [comment]
Likely fixed with this commit https://github.com/Orckestra/C1-CMS-Foundation/commit/d08fb91e

**Comment by napernik** [comment]
Fixed in C1 6.0, as well as in the **v5.6-fixes** branch
