### ISSUE TITLE
[Console Search] IE11 & Edge: Clicking a link in the search results reloads the Console

### ISSUE THREAD

**Issue by wwwysocki** [Orckestra/C1-CMS-Foundation#370]
**Repro**:

1. Use IE11 or Edge.
2. Search for something to get some pages in search results.
2. Click the link of the page in the results.

**Expected**: Taken to the page in the Content perspective
**Actual**: The Console reloads

**Workaround**: Use a different browser

**Comment by gertsonderby** [comment]
All the new UI does with this link is to access it with target="_top". So I suspect this problem is in the old UI's reaction to it.
