### ISSUE TITLE
IUserGroupPermissionDefinitions without any DefinitionPermissionTypes

### ISSUE THREAD

**Issue by slacto** [Orckestra/C1-CMS-Foundation#382]
The SQL statement below used to return nothing but somewhere between 5.0 and 6.0 I started getting entries (i.e. IUserGroupPermissionDefinitions without any DefinitionPermissionTypes). It is not a big deal but it should be fixed.

SELECT Definition.UserGroupId, Composite_Data_Types_IUserGroup.Name, Definition.SerializedEntityToken
FROM Composite_Data_Types_IUserGroupPermissionDefinition AS Definition 
INNER JOIN Composite_Data_Types_IUserGroup ON Definition.UserGroupId = Composite_Data_Types_IUserGroup.Id 
LEFT OUTER JOIN Composite_Data_Types_IUserGroupPermissionDefinitionPermissionType AS Type 
ON Definition.Id = Type.UserGroupPermissionDefinitionId
WHERE Type.PermissionTypeName IS NULL

**Comment by mawtex** [comment]
Closing this. There is no usable repro / visible negative effect, so no way we can see or fix this.
