### ISSUE TITLE
Permissions on function namespaces

### ISSUE THREAD

**Issue by slacto** [Orckestra/C1-CMS-Foundation#383]
Permissions on function namespaces will only work if similar permissions is set on at least one function in the namespace.
Example: I have a namespace called Widgets that contains 10 Razor Functions. If I set Read permissions on the namespace they will remain invisible to the editors. But if I set read permissions on a single function in the namespace then all 10 function will be visible to the editor.

**Comment by mawtex** [comment]
You should put permissions on folders in the "All Functions" tree. This is the tree that is used for "Insert Function" selection. You are very likely putting your permissions on the Razor function folder.
