### ISSUE TITLE
C1 and async MVC error: The asynchronous action method "" returns a Task, which cannot be executed synchronously.

### ISSUE THREAD

**Issue by sgedda** [Orckestra/C1-CMS-Foundation#393]
I get the following error when using composite c1 together with MVC and async actionresult. How can I solve this?

**Comment by burningice2866** [comment]
@sgedda how are you executing MVC Action? Of the top of my ahead there exists at least three different libraries which handles this

 - MVC Player
 - MVC Functions by C1Contrib
 - MVC Functions by Orchestra

**Comment by sgedda** [comment]
I use it through:
var functions = MvcFunctionRegistry.NewFunctionCollection();
functions.RegisterAction<AccountController>("Register", "Account.Register");

And then adds through composite as a function.

**Comment by burningice2866** [comment]
@sgedda Allright, then its the MVC Functions by Orchestra you're using which doesn't handle Async Actions. By looking at their source code, I'm not sure if they intended to at some point but the current codepath when executing a MVC Function ends up here https://github.com/Orckestra/CMS-Packages/blob/master/Composite.AspNet.MvcFunctions/Composite.AspNet.MvcFunctions/FunctionProvider/MvcFunctionBase.cs#L171 which handles the request synchronously.

The codepath should have ended up here https://github.com/Orckestra/CMS-Packages/blob/master/Composite.AspNet.MvcFunctions/Composite.AspNet.MvcFunctions/FunctionProvider/MvcFunctionBase.cs#L291, but i don't see any ways where that should be the case.

**Comment by burningice2866** [comment]
On a more general there is no gained performance benefit to mark ones actions used as C1 MVC Functions as async since the underlying function-engine of C1 doesn't handle awaitables and will execute each function synchronously.

**Comment by sgedda** [comment]
Ah I see! Thank you very much for the info.
