### ISSUE TITLE
[Upgrade] Page permissions lost when upgrading from C1 5.1 or older

### ISSUE THREAD

**Issue by napernik** [Orckestra/C1-CMS-Foundation#400]

**Comment by burningice2866** [comment]
Considering that it's the [DataEntityToken](https://github.com/Orckestra/C1-CMS-Foundation/blob/dev/Composite/Data/DataEntityToken.cs) itself that has been changed, i would assume that it's permissions set on all data and not just pages. Am i wrong?

**Comment by napernik** [comment]
Likely. For those data types, that do not inherit IVersioned, the serialized representation for the entity tokens should not have been changed.

**Comment by burningice2866** [comment]
@napernik isn't this issue serious enough to make a 6.0.1 release asap?

**Comment by burningice2866** [comment]
@napernik @mawtex isn't this issue serious enough to make a 6.0.1 release asap?
