### ISSUE TITLE
Class ExecuteC1Function : ExecuteC1FunctionHttpHandler not working in v5.x sites

### ISSUE THREAD

**Issue by DBailey635** [Orckestra/C1-CMS-Foundation#401]
The page at [http://docs.composite.net/Layout/LayoutFAQ?q=Can+I+call+C1+Functions+AJAX+style+from+JavaScript+or+Flash%3F](http://docs.composite.net/Layout/LayoutFAQ?q=Can+I+call+C1+Functions+AJAX+style+from+JavaScript+or+Flash%3F) states that you should be able to expose a C1 function to JavaScript / JQuery AJAX  functions via a URL. While it works fine for v4.x sites, it doesn't work for v5.x sites. The sample file on that page throws the error:

> Compiler Error Message: CS0246: The type or namespace name 'ExecuteC1FunctionHttpHandler' could not be found (are you missing a using directive or an assembly reference?)

Has this functionality been removed or changed?  How can I get this working for my v5.1 site?

**Comment by DBailey635** [comment]
My mistake! I forgot to install the ExecuteC1FunctionHttpHandler.cs file in App_Code.

Could this function be added to the main project, so that it'll work without that file?

**Comment by burningice2866** [comment]
@DBailey635 I created a package for that once, where you right-clicked a function in the Function Perspective and marked is as **Expose as Http Endpoint**, that way you don't have to fiddle with a ashx-file per function you want to call.

Let me try look for it in my library and package so one can install it as a C1 Local Package.

**Comment by DBailey635** [comment]
Thanks @burningice2866. That sounds like a great package!

**Comment by burningice2866** [comment]
@DBailey635 i managed to find the code, tidy it up at bit at publish it here https://github.com/burningice2866/CompositeC1Contrib/commit/79cc2c4c5e596a21f034a87cc8b171a1d186eab9

You can download a C1 package for local install here 
[FunctionRoutes 1.0.0.zip](https://github.com/Orckestra/C1-CMS-Foundation/files/809207/FunctionRoutes.1.0.0.zip)
