### ISSUE TITLE
Upgrading from V5.6 to V6.0 changed MVCFunctions behavior

### ISSUE THREAD

**Issue by NerdBrick** [Orckestra/C1-CMS-Foundation#403]
Our Orckestra C1 5.6 has been working wonderfully with an implementation of MVCFunctions. After upgrading a test site to V6.0 we noticed the MVC Functions don't seem to be working the same.

An example is a MVCFunction that is handling a form rendering in a page and post back. When I do a view source, the action URL that is resulting from the rendering is very different and the post back fails.

**Original MVC in view**
`@using (Html.BeginForm("Login", "Secure", new {ReturnUrl = ViewBag.ReturnUrl}, FormMethod.Post, new {  @class = "form-horizontal"}))`

**V5.6 output**
`<form id="loginForm" action="mydomain.com/Login" class="form-horizontal" method="post" novalidate="novalidate">`

**V6.0 output**
`<form id="loginForm" action="mydomain.com/Composite/api/Router?action=Login&amp;controller=Secure" class="form-horizontal" method="post" novalidate="novalidate">`

When doing the form post in V6 it will just result in a blank page. Why did the action URL expand to include a "**/Composite/api/Router**" as part of the path?

Thank you

**Comment by napernik** [comment]
The fix will be a part of the next release

**Comment by NerdBrick** [comment]
Thank you for the fast response and turn around. 

Brick

**Comment by burningice2866** [comment]
@NerdBrick remember to close/remove your related SO question http://stackoverflow.com/questions/42519021/orckestra-c1-upgrading-from-v5-6-to-v6-0-broke-mvcfunctions
