### ISSUE TITLE
Composite.AspNet.WebAPI Add-On  thrown error on CMS C1 6.00

### ISSUE THREAD

**Issue by portal7** [Orckestra/C1-CMS-Foundation#405]
I installed a fresh instance (On two distinct computers) and after success installation i decided to install "Composite.AspNet.WebAPI Addon", some seconds after, threw an exception saying 

> System.Reflection.TargetInvocationException occurred
>   HResult=0x80131604
>   Message=Exception has been thrown by the target of an invocation.
>   Source=mscorlib
>   StackTrace:
>    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
>    at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
>    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
>    at Composite.Plugins.Application.ApplicationStartupHandlers.AttributeBasedApplicationStartupHandler.AttributeBasedApplicationStartupHandler.ConfigureServices(IServiceCollection serviceCollection)
>    at Composite.Core.Application.Foundation.PluginFacades.ApplicationStartupHandlerPluginFacade.ConfigureServices(String handlerName, IServiceCollection serviceCollection)
>    at Composite.Core.Application.ApplicationStartupFacade.FireConfigureServices(IServiceCollection serviceCollection)
>    at Composite.Core.WebClient.ApplicationLevelEventHandlers.ApplicationStartInitialize(Boolean displayDebugInfo)
>    at Composite.Core.WebClient.ApplicationLevelEventHandlers.Application_Start(Object sender, EventArgs e)
>    at ASP.global_asax.Application_Start(Object sender, EventArgs e) in C:\Users\dattaguest\Downloads\C1.CMS.6.0\Website\global.asax:line 13
> 
> Inner Exception 1:
> FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
> 

Version of Instance:  6.0.6248.33161

![image](https://cloud.githubusercontent.com/assets/1530909/23598188/82f4938e-0217-11e7-9d35-05c721aeac1a.png)

**Comment by burningice2866** [comment]
You need a Binding Redirect in your web.config. Depending on your current version of Newtonsofti typically looks like this

```
<dependentAssembly>
  <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
  <bindingRedirect oldVersion="0.0.0.0-9.0.0.0" newVersion="9.0.0.0" />
</dependentAssembly>
```

added to `runtime/assemblyBinding`

**Comment by portal7** [comment]
Removed old Reference to Newtonsoft.Json 4.5 and added new reference for requested version (6.0.x) and added 

```
<dependentAssembly>
  <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
  <bindingRedirect oldVersion="0.0.0.0-9.0.0.0" newVersion="9.0.0.0" />
</dependentAssembly
```>
do the trick.

**Comment by burningice2866** [comment]
@portal7 Its because the `Composite.AspNet.WebAPI` C1 package comes with `[its own set of assemblies](https://github.com/Orckestra/CMS-Packages/tree/master/Composite.AspNet.WebAPI/Composite.AspNet.WebAPI.Package/Package/Bin)` which are years old and compiled agains an old version of `Newtonsoft.Json`. So the way .Net works, when you want to use a newer version of that assembly, is to say that everytime someone tries to reference a version of `Newtonsoft.Json` which is older than 9.0.0.0, then they should be forced to use 9.0.0.0.

**Comment by mawtex** [comment]
@portal7 I've updated the package (the WebApi/OData assemblies in it were quite dated) and the Netwonsoft.Json version is now on par with our v6 - you can grab the package here https://github.com/Orckestra/CMS-Packages/blob/master/Composite.AspNet.WebAPI/Composite.AspNet.WebAPI.Package/Release/Composite.AspNet.WebAPI.zip - let me know if you encounter any issue.

**Comment by mawtex** [comment]
The updated Composite.AspNet.WebAPI add-on is also available via the C1 Console's available packages now.

**Comment by portal7** [comment]
Testing in a new fresh instance (just right know...)...

**Comment by mawtex** [comment]
@portal7 v6.0 og netwonsoft.json is what the nuget threw at us. Thanks a lot for reporting the issue btw.

**Comment by burningice2866** [comment]
@portal7 Its good practice for library developers (Orchestra) to depend on the lower version possible and then library consumers (you) can choose to newer versions of dependencies for performance and bug fixes.

**Comment by portal7** [comment]
It is a pleasure to be able to contribute
