### ISSUE TITLE
Add Application on a page should use Configure instead of Administer Permissions

### ISSUE THREAD

**Issue by slacto** [Orckestra/C1-CMS-Foundation#408]
If I give an editor Configure permissions to a page then the editor can add page meta data and data folders but not applications (trees). 
Applications follow the Administer permission but this is not logical.
Ideally it should be possible to add separate permissions to each application tree, but if that is not possible it should use the same permission logic as page meta data and page data folders

**Comment by mawtex** [comment]
Will enable "Add Application" and "Remove Application" for users with the Configure right also. Users will the Administrate role will still have access to these actions.
