### ISSUE TITLE
"Iconified Text" Component throw Exception On Inserting

### ISSUE THREAD

**Issue by portal7** [Orckestra/C1-CMS-Foundation#413]
I'm testing the component feature when selecting the component named "Iconified Text" and inserting, application throw an Argument Exception as follow image.

FYI: new Fresh Instance:

![captura](https://cloud.githubusercontent.com/assets/1530909/23828856/0b70c91c-06be-11e7-8a78-8da727f12791.PNG)

The issue is raised because the function parameter value efectivelly not exist as named.

Here  is the code for solve it:

Filename: IconifiedText.cshtml

Line: 12

`<f:widgetfunction xmlns:f=""http://www.composite.net/ns/function/1.0"" name=""Composite.Widgets.String.FontIconSelector"">
		<f:param name=""ClassNameOptions"">
			<f:function name=""Widgets.FontIconSelector.GetIconsNames"" />
		</f:param>
		<f:param name=""StylesheetPath"" value=""~/Frontend/Orckestra/Web/Html/FontAwesome/css/font-awesome.css"" />
		<f:param name=""ClassNamePrefix"" value=""fa fa-"" />
	</f:widgetfunction>";`

**Comment by InnaBoitsun** [comment]
Hi,
Starnge, as line #12 was fixed https://github.com/Orckestra/CMS-StarterSites/blob/master/Orckestra.StarterSite.Components/Orckestra.StarterSite.Components/Package/App_Data/Razor/PageBlocks/IconifiedText.cshtml#L12 
Probably you use some old starter site install?
What Starter Site do you use?

**Comment by portal7** [comment]
Open Cph Razor, fresh clean instance

**Comment by InnaBoitsun** [comment]
I see, the issue this with Starter Site. It will be fixed.
To fix your installation
1) install the package "Orckestra.Web.Html.FontAwesome"
2) edit file _~\Frontend\Config\VisualEditor\common.xml_ and add next style reference: 
`<style file="../../Orckestra/Web/Html/FontAwesome/css/font-awesome.css"/>`

**Comment by InnaBoitsun** [comment]
Fixed
