### ISSUE TITLE
 When you try to align content, the text alignment bar does not activate on table on Visual Editor

### ISSUE THREAD

**Issue by portal7** [Orckestra/C1-CMS-Foundation#414]
When attempting to edit a text and align to the center, the toolbar button for alignment appears disabled (grayed out) and does not allow any action when editing content.

After many tries, looks like works in `<p>` tags only

![capture_edit](https://cloud.githubusercontent.com/assets/1530909/23828998/50234766-06c2-11e7-9744-251f1d87c272.PNG)

**Comment by InnaBoitsun** [comment]
Hi,

You can configure that in file ~\Frontend\Config\VisualEditor\common.xml
For now the text-center works for next tags:
`  <format id="textaligncenter" label="Center text" image="" notes="Center text" classes="text-center" selector="p, h1, h2, h3">
        <button label="" image="${icon:text-align-center}" />
      </format>`
