### ISSUE TITLE
Strong Name Composite Assembly

### ISSUE THREAD

**Issue by olihofmann** [Orckestra/C1-CMS-Foundation#415]
Hi,

Is it possible to assign a strong name to the composite assembly? All our web projects are signed.

Regards,
Oli

**Comment by mawtex** [comment]
We are not planning to strong name the assemblies in C1 CMS. You can use the "Source code (zip)" link on https://github.com/Orckestra/C1-CMS-Foundation/releases to fetch the source code / projects for the release you with to strong name and set up the projects to emit signed assemblies.

**Comment by srudin** [comment]
I would also be interested in having this fixed.
May I ask why you are not planning to do this? It is widely accepted to be a good practice to sn your assemblies (https://msdn.microsoft.com/en-us/library/ms182127.aspx) and while it is very easy to do so it causes a lot of troubles for anyone else when it isn't done. So what is the reason?

**Comment by mawtex** [comment]
One reason is that we are dependent on 3rd party assemblies  and they'd all need to be available strong named as well. If you look into it and find a very easy way to do it, send a pull request :)
