### ISSUE TITLE
C1 5.5 and EF 6.0

### ISSUE THREAD

**Issue by olihofmann** [Orckestra/C1-CMS-Foundation#424]
Hi,

I have a problem. I use EF 6.0 in my C1 Website, after install my package with the EF DLL i have this error

Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.

Can you help me, please?

Regards,
Oli

**Comment by napernik** [comment]
The website is missing some of the required dll-s, or dll versions do not match up. It is likely can be solved with adding the missing dll-s or adding assemlby bindings to the /Web.config. Do you have the whole exception text with the call stack?
