### ISSUE TITLE
[Components] Components window is empty when site is running in subfolder

### ISSUE THREAD

**Issue by InnaBoitsun** [Orckestra/C1-CMS-Foundation#426]
**How to reproduce:**
1. Set up C1 site to be run in subfolder, so the url to console will look like this: _http://localhost/sub/Composite/top.aspx_
2. In console edit some page, click on "Components" button

**Expected:** Components are visible and can be selected
**Actual:** Components window is empty

Looks like some JS files can't be loaded, because they have wrong URL: 
_http://localhost:/Composite/lib/babel/browser-polyfill.js
http://localhost/Composite/console.js_

**Comment by jonasritzmo** [comment]
This is not working for me. If I take the latest dev code and compile it and then run it from IIS Default Web Site / My Application it is not using the index.prod.html file. The components button using index.html. If I change the code in index.html so it looks like index.prod.html it is still not working.
The file console.js is located under folder Console so the link should be console.js and not ../console.js?

Br,
Jonas Ritzmo

**Comment by neexite** [comment]
Dev version is not prepeared to running in subfolder yet.
If you want to run dev version you can try use compiled /Composite/console.js (and copy index.prod.html to index,html)
You can get /Composite/console.js in two ways: 
 a) from production copy of CMS
 b) run "npm run buildconsole" from website folder 

If you want to use non-compiled ReactJS than you need to change "baseURL": "/"  to "baseURL": "/My%20Application/" in jspm.config.js, and change paths in index.html

**Comment by jonasritzmo** [comment]
Thanks for the help! Now it works fine!
