### ISSUE TITLE
Cannot load solution in Visual Studio 2017

### ISSUE THREAD

**Issue by steadycoding** [Orckestra/C1-CMS-Foundation#429]
**The following migration report is generated when trying to open the source zip with Visual Studio 2017.**

None of the projects are loaded with Composite and Composite.Workflows labeled as incompatible and Website being loaded as load failed. Finally an error with the tooling is found in the output. 

`C:\C1-CMS-Foundation-6.0\Website\WebSite.csproj : error  : The imported project "$(VSToolsPath)\WebApplications\Microsoft.WebApplication.targets" was not found. Also, tried to find "$(VSToolsPath)\WebApplications\Microsoft.WebApplication.targets" in the fallback search path(s) for $(VSToolsPath) - "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v15.0" . These search paths are defined in "C:\Users\<userame>\AppData\Local\Microsoft\VisualStudio\15.0_0b5b17e6\devenv.exe.config". Confirm that the path in the <Import> declaration is correct, and that the file exists on disk in one of the search paths.  E:\C1-CMS-Foundation-6.0\Website\WebSite.csproj`

![image](https://cloud.githubusercontent.com/assets/17366068/24982317/c223b986-1f95-11e7-87fd-3fc184d7b0bf.png)

**Comment by napernik** [comment]
There are a few components that has to be installed to the visual studio, in order for it to support the old version of Windows Workflow Foundation that is used in those projects.

Please check that the following components are present:

.NET Framework 4.6.1 SDK
.NET Framework 4.6.1 targeting pack
C# and Visual Basic Roslyn compilers
MSBuild
Windows Workflow Foundation
Blend for Visual Studio SDK for .NET
Visual Studio SDK
