### ISSUE TITLE
Subroutes not found when using AspNet.MvcFunctions

### ISSUE THREAD

**Issue by identify1980** [Orckestra/C1-CMS-Foundation#430]
[Cross-Posted with the packages-repository]

Since using the current C1 6.0 (patched with bugfix-branch, which also solved another issue listed here somewhere concerning POST for forms within an MVC function) I can call pages with an mvc function in it. However - if the MVC function is registered via class attribute and there are sub actions in the controller I cannot access them anymore. It definitely worked with v5.0

Some example code below:

`
[C1Function(Namespace = "T2G.Account", Name = "Login", Description = "Displays a login form")]
public class LoginController : Controller
{
	[AllowAnonymous]
	public ActionResult Index(string returnUrl)
	{
		// some code
	}

	[AllowAnonymous]
	[HttpPost]
	[ValidateAntiForgeryToken]
	public ActionResult Index(UserLoginViewModel model)
	{
		// some code
		return this.RedirectToAction(
			"SendCode",
			new
			{
				rememberMe = model.RememberMe,
				returnUrl =
					string.IsNullOrWhiteSpace(returnUrl)
						? string.Empty
						: HttpUtility.UrlEncode(returnUrl)
			});
	}

	[AllowAnonymous]
	public ActionResult SendCode(bool rememberMe, string returnUrl)
	{
		// some code
	}
}
`

The page has the url "Login". The login form gets displayed. The POST also happens. But when I get redirected to "SendCode" ("/Login/SendCode?rememberMe=False"), I just get a 404.

**Comment by napernik** [comment]
Hi @identify1980 

Which version of the Composite.AspNet.MvcFunctions package are you using? 
You can check it by right-clicking Properties on the /bin/Composite.AspNet.MvcFunctions.dll file.
The latest one is 1.0.12.

I tried reproducing it locally, and the only problem I found was that the "returnUrl" may get incorrectly encoded during a redirect, which I will look into fixing for.

Also, in your case - it is not obvious whether the page on which the function is placed has url "/Login" or a different one. 

The code I used:

```
    [C1Function(Namespace = "T2G.Account", Name = "Login", Description = "Displays a login form")]
    public class LoginController : Controller
    {
        [AllowAnonymous]
        public ActionResult Index(string returnUrl)
        {
            return View();
        }

        [AllowAnonymous]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult RedirectTest()
        {
            // some code
            return this.RedirectToAction(
                nameof(SendCode),
                new
                {
                    rememberMe = true,
                    returnUrl = "https://google.com"
                });
        }

        [AllowAnonymous]
        public ActionResult SendCode(bool rememberMe, string returnUrl)
        {
            return View(new { rememberMe = rememberMe, returnUrl = returnUrl});
        }
    }
```

Index.chtml:

```
@model dynamic

<h1>Index view</h1>
<p>
    <form action="/Login/RedirectTest" method="post">
        <button type="submit">Submit !</button>

        @Html.AntiForgeryToken() 
    </form>
</p>
```


SendCode.cshtml:

```
@model dynamic

<h1>Send Code view</h1>

<div>
    RembemberMe = @Model.ToString()
</div>
```

**Comment by identify1980** [comment]
Hi @napernik : well - dll is showing me 1.0.13 as version. The page has "Login" as URL-Name - so the path is "/Login". The page has the MVC function included to the content - doing a form post to itself (and as in code: redirect to its "SendCode" action)

**Comment by napernik** [comment]
I assuming that the result action url is actually correct, but it isn't resolved correctly for some reason.  It could be either something related to the controller itself or something related to the route registration.

Can you attach here the controller code along with the razor views, so I can check it locally?

I've uploaded a newer version of the package - 1.0.14 it addresses "returnUrl" parameter not being encoded correctly.

**Comment by napernik** [comment]
Closed due to inactivity
