### ISSUE TITLE
[C1 6.1] Inline C# code defined in <msxsl:script ... /> doesn't work for XSLT functions

### ISSUE THREAD

**Issue by napernik** [Orckestra/C1-CMS-Foundation#440]
The exception is "Cannot find a script or an extension object associated with namespace '{....}"

Test case - Composite.Navigation.HttpsEnforcer package is not working.

<xsl:stylesheet ... xmlns:csharp="http://c1.composite.net/csharp"...>
	<msxsl:script implements-prefix="csharp" language="C#" xmlns:msxsl="urn:schemas-microsoft-com:xslt">
		...
	</msxsl:script>

**Comment by napernik** [comment]
We have a fix - to replace /Bin/Orckestra.AspNet.Roslyn.dll with the attached one:
[Orckestra.AspNet.Roslyn.dll.zip](https://github.com/Orckestra/C1-CMS-Foundation/files/992573/Orckestra.AspNet.Roslyn.dll.zip)

**Comment by burningice2866** [comment]
@napernik can we expect an updated NuGet package and updated version-reference here https://github.com/Orckestra/C1-CMS-Foundation/blob/dev/Website/packages.config#L21 ?

**Comment by napernik** [comment]
yes, the NuGet is a bit slow though. I'm waiting to the package to be visible. The sources are in the C1-Packages now.

**Comment by burningice2866** [comment]
Btw, https://www.nuget.org/packages/Microsoft.CodeAnalysis.CSharp/ is out in a version 2.1. You should have updated the dependency to that.

**Comment by napernik** [comment]
Just looked at the updated Microsoft.CodeAnalysis.CSharp - not much changed but the version, even the dll sizes are the same :)

**Comment by burningice2866** [comment]
Even though `Microsoft.CodeAnalysis.CSharp` itself haven't changed, the whole array of underlying dependent assemblies that make up Roslyn has been updated as well.
