### ISSUE TITLE
Style sheets are not displayed in the admin console when an external template is deployed

### ISSUE THREAD

**Issue by portal7** [Orckestra/C1-CMS-Foundation#444]
I implementing a Template in a new Instance of C1 CMS, and looks fine as you can see here....
![image](https://cloud.githubusercontent.com/assets/1530909/26426221/133ad7d0-40ae-11e7-9cee-8e18f0362b76.png)

But when the administration console is loaded (like the following screen capture), no stylesheet is loaded because the url are broken

![image](https://cloud.githubusercontent.com/assets/1530909/26426345/8a64cd2a-40ae-11e7-9130-3efd02e0bcd2.png)

**Comment by mawtex** [comment]
Is your css included using absolute paths, like ~/css/site.css?
If that's not the issue, please dive into one of those 404s - what does the request and response headers say? Anything interesting in the c1 server log?

**Comment by portal7** [comment]
my bad....is not a bug... so sorry
`~/`
do the trick.
