### ISSUE TITLE
Unhandled Cross Origin exception when previewing a page on sub domain

### ISSUE THREAD

**Issue by burningice2866** [Orckestra/C1-CMS-Foundation#448]
Consider this scenario;

 - A solution running on domain **corp.com** has a Tree inside the cms which previews documents on a subdomain upon selecting an item.
 - The preview-url is resolved by a redirect so first we request **corp.com/linkredir?123** which redirects to **intranet.corp.com/123**
 - Due to the preview happening from a different domain we get a Cross Origin error
 - This error isn't handled properly and makes the Console unstable
    - Ie. editng a item opens a new tab but no content is shown in it.
    - Only solution when this happens is to refresh the Console

```
Uncaught DOMException: Blocked a frame with origin "https://atriumcph.com" from accessing a cross-origin frame.
    at WindowBinding.getContentDocument (https://atriumcph.com/Composite/scripts/compressed/top.js?timestamp=319182552&c1=6.1.6325.31805:29:1974)
    at BrowserTabBoxBinding.getLocation (https://atriumcph.com/Composite/content/views/browser/BrowserTabBoxBinding.js?c1=6.1.6325.31805:189:26)
    at BrowserPageBinding.pushURL (https://atriumcph.com/Composite/content/views/browser/BrowserPageBinding.js?c1=6.1.6325.31805:401:30)
    at https://atriumcph.com/Composite/content/views/browser/BrowserPageBinding.js?c1=6.1.6325.31805:373:15
```

**Comment by mawtex** [comment]
A possible workaround could be to make **corp.com/linkredir?123** respond with a simple HTML page containing a full width/height iframe, which then loads **intranet.corp.com/123** - I haven't tested this, but since the CMS Console likely won't interact with that iframe, no cross origin errors should happen.

**Comment by neexite** [comment]
1) Which type of redirect used (http header, js redirect)?
2) Did you test on new fix 1169400, it also contains fix for previewing in the tree.

**Comment by burningice2866** [comment]
@neexite 

1. Its a server side (http header) redirect
2. This issue is also about previewing in the tree and yes, the fix solves this issue as well since its 100% the same as https://github.com/Orckestra/C1-CMS-Foundation/issues/451

**Comment by napernik** [comment]
Yes, if it the same and the fix works  we can close it :)
