### ISSUE TITLE
Console stops working properly if a previewing a page does a redirect to an external website.

### ISSUE THREAD

**Issue by napernik** [Orckestra/C1-CMS-Foundation#451]
Repro:
1) Create a page
2) Put the following function markup inside 
```
<f:function name="Composite.Web.Response.Redirect" xmlns:f="http://www.composite.net/ns/function/1.0">
			<f:param name="Url" value="http://compositec1.codeplex.com/discussions" />
		</f:function>
```
3) Press "Save & Publish"
4) Click back to the content tree
Expected: console is working
Actual: it is not possible neither to preview nor to edit any other page because of javascript errors

**Comment by burningice2866** [comment]
Is it related to https://github.com/Orckestra/C1-CMS-Foundation/issues/448 due to a unhandled Cross Origin exception?

**Comment by napernik** [comment]
Those manifest similarly, but are 2 different issues. 
Previewing another C1 page should use a relative URL when domains aren't matched. It it is not happening, that's one bug, console not working for foreign domains - another.

**Comment by burningice2866** [comment]
@napernik issue #448 is not about previewing another C1 page, but an arbitrary element via a custom EntityTokenToUrl mapper, where the data represents data contained on a different domain and therefor renders a page from a different domain.
