### ISSUE TITLE
Error accessing composite application -> Server Error in '/Composite' Application after upgrading

### ISSUE THREAD

**Issue by askmesql** [Orckestra/C1-CMS-Foundation#457]
I dont have a service plan, I was doing the manual upgrade. 
- took the backup of the site
-took the website offline 
-installed the latest version of c1 under the website
-when the website was up and running it didnt work 
So, I restored a backup of our website to test the upgrade process. Website worked fine, but when i tried accessing the Composite application, I got the following error 
"Could not load file or assembly 'Composite' or one of its dependencies. The system cannot find the file specified"

-> I have ensured that the application pool has full permission on the IIS Site. 
-> Right click on 'Composite' folder and made it an application. 
Website otherwise works fine on both production and Test. Composute runs fine in procuction too. 

I access the application and composite thru : https://localhost/Composite  -> virtual directory points to the right folder 

from the log, it seems like tying to access files in Composite\bin,  app_data  and some other directories whcih dont exist earlier or on the running version in production 

Here is the log 

=== Pre-bind state information ===
LOG: DisplayName = Composite
 (Partial)
WRN: Partial binding information was supplied for an assembly:
WRN: Assembly Name: Composite | Domain ID: 3
WRN: A partial bind occurs when only part of the assembly display name is provided.
WRN: This might result in the binder loading an incorrect assembly.
WRN: It is recommended to provide a fully specified textual identity for the assembly,
WRN: that consists of the simple name, version, culture, and public key token.
WRN: See whitepaper http://go.microsoft.com/fwlink/?LinkId=109270 for more information and common solutions to this issue.
LOG: Appbase = file:///D:/IISSites/TestAppp/Composite/
LOG: Initial PrivatePath = D:\IISSites\TestAppp\Composite\bin
Calling assembly : (Unknown).
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: D:\IISSites\TestAppp\Composite\web.config
LOG: Using host configuration file: C:\Windows\Microsoft.NET\Framework64\v4.0.30319\aspnet.config
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework64\v4.0.30319\config\machine.config.
LOG: Policy not being applied to reference at this time (private, custom, partial, or location-based assembly bind).
LOG: Attempting download of new URL file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/Temporary ASP.NET Files/composite/b008b3c3/9b869bc2/Composite.DLL.
LOG: Attempting download of new URL file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/Temporary ASP.NET Files/composite/b008b3c3/9b869bc2/Composite/Composite.DLL.
LOG: Attempting download of new URL file:///D:/IISSites/TestAppp/Composite/bin/Composite.DLL.
LOG: Attempting download of new URL file:///D:/IISSites/TestAppp/Composite/bin/Composite/Composite.DLL.
LOG: Attempting download of new URL file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/Temporary ASP.NET Files/composite/b008b3c3/9b869bc2/Composite.EXE.
LOG: Attempting download of new URL file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/Temporary ASP.NET Files/composite/b008b3c3/9b869bc2/Composite/Composite.EXE.
LOG: Attempting download of new URL file:///D:/IISSites/TestAppp/Composite/bin/Composite.EXE.
LOG: Attempting download of new URL file:///D:/IISSites/TestAppp/Composite/bin/Composite/Composite.EXE.

  

Stack Trace: 

[FileNotFoundException: Could not load file or assembly 'Composite' or one of its dependencies. The system cannot find the file specified.]
   System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMarkHandle stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName, ObjectHandleOnStack type) +0
   System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName) +106
   System.RuntimeType.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark) +62
   System.Type.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase) +50
   System.Web.Compilation.BuildManager.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase) +61
   System.Web.Configuration.ConfigUtil.GetType(String typeName, String propertyName, ConfigurationElement configElement, XmlNode node, Boolean checkAptcaBit, Boolean ignoreCase) +53

[ConfigurationErrorsException: Could not load file or assembly 'Composite' or one of its dependencies. The system cannot find the file specified.]
   System.Web.Configuration.ConfigUtil.GetType(String typeName, String propertyName, ConfigurationElement configElement, XmlNode node, Boolean checkAptcaBit, Boolean ignoreCase) +587
   System.Web.Configuration.ConfigUtil.GetType(String typeName, String propertyName, ConfigurationElement configElement, Boolean checkAptcaBit) +33
   System.Web.Configuration.Common.ModulesEntry.SecureGetType(String typeName, String propertyName, ConfigurationElement configElement) +57
   System.Web.Configuration.Common.ModulesEntry..ctor(String name, String typeName, String propertyName, ConfigurationElement configElement) +54
   System.Web.HttpApplication.BuildIntegratedModuleCollection(List`1 moduleList) +198
   System.Web.HttpApplication.GetModuleCollection(IntPtr appContext) +1114
   System.Web.HttpApplication.RegisterEventSubscriptionsWithIIS(IntPtr appContext, HttpContext context, MethodInfo[] handlers) +140
   System.Web.HttpApplication.InitSpecial(HttpApplicationState state, MethodInfo[] handlers, IntPtr appContext, HttpContext context) +172
   System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(IntPtr appContext, HttpContext context) +402
   System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext) +343

[HttpException (0x80004005): Could not load file or assembly 'Composite' or one of its dependencies. The system cannot find the file specified.]
   System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +539
   System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +125
   System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +731

**Comment by mawtex** [comment]
The /Composite folder should not be an application in IIS. It should just be a vanilla sub folder.

**Comment by askmesql** [comment]
Thanks Mawtex, that worked. i'm not sure why i made it an application. :)
