### ISSUE TITLE
SQL Data Provider Performance

### ISSUE THREAD

**Issue by ai-fwd** [Orckestra/C1-CMS-Foundation#465]
I'm just in the process of migrating my C1 4.3 XML instance to SQL. When I trace the calls C1 makes to the DB it seems to make sense for reads. However, saving edits (i.e. IPagePlaceholderContent.*) makes at least 100 calls to the DB. 

From what i can tell, it basically saves the entire view back into the DB by first deleting the objects and then recreating them. Is there a reason for this pattern? I would have expected it to maintain state and then only commit the dirty entries to the DB via an Update.

On an S2 instance of SQL Azure with 1 user saving it spikes CPU % to 60%. Are there any ways to optimize this?

On an S3 the DTUs don't spike as much but it still seems to take at least 20 seconds per save which seems excessive.

**Comment by ai-fwd** [comment]
FYI - On an S3 the DTUs don't spike as much but it still seems to take at least 20 seconds per save which seems excessive.

**Comment by ai-fwd** [comment]
After looking at the code more closely it seems the issue is that any update of a page triggers the following:

1. All metadata and datafolders are queried
2. All (1) are updated with a PublicationStatus regardless of any edits or existing [PublicationStatus]
3. Page is updated
4. Each page placeholder is updated
5. For every entity it's then DELETED and then INSERT to be in the Pubic DataScope
6. Additional inserts are made to track Flow

For me, this equates to around 20-46 individual queries to the DB which don't spike the DTUs (Azure S3) but take anywhere between 17-30 seconds depending on the page complexity/queries. 

Can someone confirm I haven't done something wrong in my migration to SQL and this chattiness is something everyone is experiencing?

**Comment by mawtex** [comment]
v4.3 is some two years old, so checking the status using a recent release could make sense. This is not something we have seen be an issue.

**Comment by ai-fwd** [comment]
@mawtex the code to write persist changes using the SQL provider exists the following files:

1. Composite.Plugins.Elements.ElementProviders.PageElementProvider.EditPageWorkflow
2. Composite.Plugins.Data.DataProviders.MSSqlServerDataProvider.SqlDataTypeStoresContainer
3. Composite.Data.ProcessControlled.ProcessControllers.GenericPublishProcessController.GenericPublishProcessController

Since v4.3 there have been so significant updates to this workflow. 

If you click [here](https://github.com/Orckestra/C1-CMS-Foundation/blob/e84641e29e28faaf08001e204f50b0de1cebe7a8/Composite.Workflows/Plugins/Elements/ElementProviders/PageElementProvider/EditPageWorkflow.cs#L349) you'll see where it iterates through the metadata one by one.

If you click [here](https://github.com/Orckestra/C1-CMS-Foundation/blob/e84641e29e28faaf08001e204f50b0de1cebe7a8/Composite/Data/ProcessControlled/ProcessControllers/GenericPublishProcessController/GenericPublishProcessController.cs#L492) you'll see how it forces a delete and then insert to change the DataScope

I believe that if you create a C1 website with 9 datafolders + metadata tree links and run a trace on a local DB you'll see the exact same behavior regardless of the version.

**Comment by mawtex** [comment]
The way we update is as you describe, but the response times you describe (up to 46 queries taking up to 30 seconds) is not something we have seen. 

I guess this is environment specific? Or have you seen this when running on a local setup with a local SQL Server?

**Comment by ai-fwd** [comment]
@mawtex local is going to be faster without question but still takes a good few seconds locally as well when it really should be batching the calls. 

In azure both the DB and Website are in the same Data Center so there isn't much else i can do there.

**Comment by ai-fwd** [comment]
I'm looking at optimizing things for my own purposes and the only area i think i could help speed things up is within Composite.Data.ProcessControlled.ProcessControllers.GenericPublishProcessController.GenericPublishProcessController.OnAfterDataUpdated

It seems that this code is executed after every Update but only continuing to Delete and then AddNew on the publish workflow. For all the MetaData types i have attached to a page it seems that it simply delete's it and then adds it back into the database. No value changes to the DB.

The only reason i think i'm  not understanding this code is because of what happens with [Composite_Data_Types_IPagePlaceholderContent_en_US] table. For these objects it doesn't Delete them but Adds them only. When i query the tables directly i can clearly see they are there but yet the "existing" variable always come back as empty (for these case only).

Can someone explain to me what's going on in this code block? I know it has something to do with the DataScope but i can't figure out how it's able to query the table and not find the row when it's clearly there. Then after that it's able to Add/Insert the entry back but again -- it was always there. I see the Insert call happening yet no error is reported (i.e. duplicate key) and there is no DELETE call either.

**Comment by mawtex** [comment]
@ai-fwd 10 seconds to save a page is not something we've experienced, so we would need to take a closer look to identify the issue. My gut feeling is that this really isn't connected with the number of SQL calls (unless the SQL Server is awfully slow).

Things that could cause a severe performance degradation (beyond a slow SQL Server): 
 * custom code attached to [data update events](https://api.cms.orckestra.com/?topic=html/AllMembers_T_Composite_Data_DataEvents_1.htm) which take a long time to complete, 
 * huge row count  - we seen .NET performance degrade dramatically, when having 10K+ items in a hash table (on 64bit app pools - 20K+ item limit on 32bit app pools). If you have a table with more than 10K rows, this could be a limit you are hitting.
 * large / slow console tree structures that update when the page is updated

**Comment by ai-fwd** [comment]
@mawtex so far what I've found to be the biggest impact is that in the admin console root pages that are unpublished are constantly queried for after every operation. These are never added to the cache like unpublished pages are when rendering a site so every cache miss (we had 65) fired of a call to the DB.

Simpler optimizations like adding the cache attribute on custom data types that are used as page metadata increasing the cache size helped as well. 

You mention huge row counts being an issue but I've had to double the cache sizes for Pages, Page Structure and Child Pages. I haven't noticed any issues so far when in the 20K+ range. Where did your team notice the slow downs?

**Comment by mawtex** [comment]
@ai-fwd allowing in-mem caching of your own data types will indeed speed things up. If you came across perf optimizations in the C1 core as well, do share :)

> Where did your team notice the slow downs?

We've seen some systems have a sudden perf degradation when hitting some limit (more related to total size than number of elements as I wrote). Described here https://blogs.msdn.microsoft.com/maoni/2016/05/31/large-object-heap-uncovered-from-an-old-msdn-article/ - a quick fix here can be to change the appPool to run 32-bit

**Comment by ai-fwd** [comment]
@mawtex you guys made a big optimization [here](https://github.com/Orckestra/C1-CMS-Foundation/commit/26fb4f887288440db9277fb245e21a0339a8c841) for when pages are published in the CMS. 

Was there a reason why you didn't implement the same logic for "saving" an unpublished page? When that happens it still invalidates the entire "adminstrated" cache even though it was a single page that got touched. I'll likely have to add that but i'm just wondering why you guys chose against it as part of the above.

**Comment by napernik** [comment]
Hi @ai-fwd 

The mentioned commit was meant to have just the minimal changes to address a specific issue rather than an attempt to make a general optimization. The issue was that one of our customers weren't able to delete multiple pages at once due to SQL transaction timeouts.

> Was there a reason why you didn't implement the same logic for "saving" an unpublished page? When that happens it still invalidates the entire "adminstrated" cache even though it was a single page that got touched. 

It is actually already implemented, I've pushed a commit a few hours ago

https://github.com/Orckestra/C1-CMS-Foundation/commit/34134e465786a9b121bfdad59687a7e0290d674a

Along with this commit, it should noticeably improve the console performance

https://github.com/Orckestra/C1-CMS-Foundation/commit/6548e6ccec1b07a34f11b1f6ee33817c076909d2

**Comment by ai-fwd** [comment]
@napernik awesome thanks! Out of curiosity are you supporting customers with a high number of subsites, or a large number of pages?

**Comment by burningice2866** [comment]
@ai-fwd http://www.dhf.dk/ used to be the largest installation counted in subsites, pages and media files. Several optimizations have been made based on this installation. I don't know though if its still the biggest though after C1 was acquired by Orckestra.

Number of subsites varies but is 10+
Number of pages and media files are 20.000+

**Comment by ai-fwd** [comment]
@napernik those changes helped a lot. Since we have a large # of subsites i noticed that whenever the console loaded it needed to query for all root homepages by getting the child ids (of empty guid) and then iterating through the list for each one. That would issue a lot of querys to the DB and because we're using SQL azure it would eat up DTUs.

To optimize it I've implemented the following in PageManager.cs

```C#
public static IEnumerable<IPage> GetPagesById(IEnumerable<Guid> ids)
        {
            var result = new List<IPage>();
            var cacheMisses = new List<Guid>();

            //Pull the pages from the cache, if we miss then remember it
            foreach (var id in ids)
            {
                var cacheKey = GetCacheKey<IPage>(id);
                var cachedValue = _pageCache.Get(cacheKey);

                if (cachedValue != null)
                {
                    result.Add(cachedValue.Value);
                }
                else
                {
                    cacheMisses.Add(id);
                }
            }

            
            if (cacheMisses.Any())
            {
                var cacheMissResults = DataFacade.GetData<IPage>(false).Where(q => cacheMisses.Contains(q.Id)).ToList();
                result.AddRange(cacheMissResults);
                cacheMissResults.ForEach(q=>_pageCache.Add(GetCacheKey<IPage>(q.Id), new ExtendedNullable<IPage>{Value = q}));
            }

            return result.Any() ? result : null;
        }
```

In PageServices i've updated the code to call it:

```C#
public static IQueryable<IPage> GetChildren(Guid parentId)
        {
            var pageIDs = PageManager.GetChildrenIDs(parentId);

            var result = new List<IPage>();

            foreach (var page in PageManager.GetPagesById(pageIDs))
            {
                // A page can de deleted after getting the child list, in a separate thread
                if (page != null)
                {
                    result.Add(page);
                }
            }

            return result.AsQueryable();
        }
```

The next optimization was again to do around getting root pages. This time it was in the ElementFacade.cs where after getting all the root pages (using the cache) it [here](https://github.com/Orckestra/C1-CMS-Foundation/blob/dev/Composite/C1Console/Elements/ElementFacade.cs#L343) ends up making it's way to [Composite.Data.DataFacadeImpl.GetDataFromDataSourceId](https://github.com/Orckestra/C1-CMS-Foundation/blob/dev/Composite/Data/DataFacadeImpl.cs#L116) which uses a different cache. Since children in ElementFacade contains all root pages it ends up querying the DB children.count() times hydrating the cache. 

Right after that it wants to [perform a security check](https://github.com/Orckestra/C1-CMS-Foundation/blob/dev/Composite/Data/DataFacadeImpl.cs#L116) to make sure you have permission to the children. My optimization was to move that up above [here](https://github.com/Orckestra/C1-CMS-Foundation/blob/dev/Composite/C1Console/Elements/ElementFacade.cs#L331) so it first filters the children and then continues along.

Do you agree with these optimizations and would it be worthwhile to create a PR for you?

**Comment by napernik** [comment]
At the moment the PageServices.GetChildren has already been optimized a bit (since 4.3), no need for a check in as you already pasted the code and I'll have to do more testing on XML vs SQL data provider to see what's the best implementation for each.

https://github.com/Orckestra/C1-CMS-Foundation/blob/efe7f1c566d2ccaac789cb6787e8b1b4f5ee31b7/Composite/Data/Types/PageServices.cs#L67

But I can already see that your implementation should allocate much less memory. It is also interesting that the following code works at all

var cacheMisses = new List<Guid>();
var cacheMissResults = DataFacade.GetData<IPage>(false).Where(q => cacheMisses.Contains(q.Id)).ToList();

With the previous versions of .NET framework, it would throw an exception that List<T>.Contains(...) method doesn't have a translation to SQL, if it works now, it opens up quite a bit of optimization opportunities :)

------------

> Right after that it wants to perform a security check to make sure you have permission to the children. My optimization was to move that up above here so it first filters the children and then continues along.

FilterAction() both filters the element and the action tokens, if you move it up, it the actions won't be filtered correctly.

At the moment the sequence is:

1) Getting the child elements
2) Calculating if they have children as well
3) Adding actions
4) Filtering elements and actions

I guess an optimized sequence would be:

1) Getting the child elements
2) Filtering elements
3) Calculating if they have children as well
4) Adding actions
5) Filtering actions

I'll look into this one as well.

Btw, you can consider having your customized C1 build published to GitHub, this way you can send a link to your code directly.

**Comment by burningice2866** [comment]
@napernik 

```
var cacheMisses = new List();
var cacheMissResults = DataFacade.GetData(false).Where(q => cacheMisses.Contains(q.Id)).ToList();
```

As long as the list you're calling `Contains` on is list of simple values, AFAIK its always been possible to translate that into SQL since that will become an IN operator like

```
SELECT column_name(s)
FROM table_name
WHERE column_name IN (value1, value2, ...);
```

**Comment by ai-fwd** [comment]
@napernik yes I've use the Contains approach a lot and as @burningice2866 mentioned it should work on simple values.

Regarding FilterAction -- thanks for letting me know. Would it just be something simple like this:

```C#
public static IEnumerable<Element> FilterElements(this IEnumerable<Element> elements)
        {
            if (elements == null) throw new ArgumentNullException("elements");

#if NO_SECURITY
                return elements;
#else
            UserToken userToken = UserValidationFacade.GetUserToken();

            IEnumerable<UserPermissionDefinition> userPermissionDefinitions =
                PermissionTypeFacade.GetUserPermissionDefinitions(userToken.Username);
            IEnumerable<UserGroupPermissionDefinition> userGroupPermissionDefinition =
                PermissionTypeFacade.GetUserGroupPermissionDefinitions(userToken.Username);

            foreach (Element element in elements)
            {
                if (PermissionTypeFacade.IsSubBrachContainingPermissionTypes(userToken,
                    element.ElementHandle.EntityToken, userPermissionDefinitions, userGroupPermissionDefinition))
                {
                    yield return element;
                }
            }
        }
```

and then FilterActions remains as is except we remove the `IsSubBrachContainingPermissionTypes` check?

**Comment by napernik** [comment]
Yes. The change is rather small, so I've applied it

https://github.com/Orckestra/C1-CMS-Foundation/commit/0d1cae981227065ee4d6c2e175318d63cb280279

**Comment by ai-fwd** [comment]
@napernik thanks! It does optimize the code but unfortunately FilterElements is called regularly in order to refresh the UI (i.e. adding a function wants to redraw the Website tree).

The three points of potential optimization would be in the top.js where maybe we don't need to refresh the whole UI when an element is loaded on screen, or  ElementFacade.GetChildren to cache the FilterElement's result or in the IsSubBrachContainingPermissionTypes call which figures out what you have permissions too. 

What do you think would be the best option? My thinking is to create a new Cache (inline with PermissionTypeFacadeCaching.cs) to store the results of IsSubBrachContainingPermissionTypes to speed up the operation.

**Comment by ai-fwd** [comment]
@mawtex it's a simple as you are probably thinking.

1. Edit page
2. Insert -> Function
3. It calls TreeServices.asmx (via. GetElementsBySearchToken) for the select function popup 
4. It calls TreeServices.asmx (via. FindEntityToken with openNodes being the "Website") and it seems to call it twice.

**Comment by napernik** [comment]
Yes, fixing the function refresh is a probably the way to go. Also in C1 6.0 and newer we use the components instead of functions - where you have a searchable list of components to insert, instead of a function tree. So that may not be an issue in the newer versions.

Most of the things in IsSubBrachContainingPermissionTypes are already cached/optimized. How many different permissions do you have on your websites (IUserPermissionDefinition, IUserGroupPermissionDefinition data types) ? 

I would recommend upgrading to recent release and running a profiler to see what takes time and how many calls are made to each method ( I use JetBrains' DotTrace )

**Comment by burningice2866** [comment]
> we use the components instead of functions

That sounds like a bold statement !? I don't know of anyone that sees Components as a replacement to inserting functions and not just a complimentary feature.

**Comment by ai-fwd** [comment]
@napernik IUserPermissionDefinitions is around 35, and IUserGroupPermissionDefinition is around 89. As you know it loops through the number of Root homepages so that gives us O(nm) where n is root homepages, and m = IUserPermissionDefinitions + IUserGroupPermissionDefinition.

_yes i broke out the O notation :)_

**Comment by napernik** [comment]
> yes i broke out the O notation :)

The O-notation is the best kind of notation :)
I quickly look in to the code, it loops only through permissions relevant to the current user and its user groups, so the complexity isn't that bad.  

> It seems like the PermissionTypeFacadeCaching might actually be meant for this very thing. Since if i'm remembering (don't have it in front of me) the PermissionTypeFacade takes the UserToken and Entity and returns back the perms on it. Am i reading it wrong, or could it be used here as well?

IsSubBrachContainingPermissionTypes is already using PermissionTypeFacadeCaching to cache all of the evaluated permissions, but now I can see that it is implemented using RequestLifetimeCache and the values are cached for a single request at a time only. 

You can try to change the implementation to use Composite.Data.Caching.Cache or just HttpApplication.Cache to see if it would improve the performance.

**Comment by mawtex** [comment]
> You can try to change the implementation to use Composite.Data.Caching.Cache or just HttpApplication.Cache to see if it would improve the performance.

Which introduce the wonderful task of cache invalidation...

**Comment by burningice2866** [comment]
> Which introduce the wonderful task of cache invalidation...

One of the two hardest concepts in programming, next after naming and off-by-one errors.

**Comment by ai-fwd** [comment]
> I quickly look in to the code, it loops only through permissions relevant to the current user and its user groups, so the complexity isn't that bad.

OK so i think the issue here is the number of root homepages (N) then since it is scoped to just the user's permissions but has to do the check N times. The other fixes have helped speed things up a lot so I'll look into changing the caching when this becomes a bigger issue.

I'm happy to close this. Appreciate all the help.
