### ISSUE TITLE
How to store GeoCoordinate - there is no Double

### ISSUE THREAD

**Issue by aeont** [Orckestra/C1-CMS-Foundation#468]
> namespace Composite.Data
{
    [EditorBrowsable(EditorBrowsableState.Never)]
    public enum PhysicalStoreFieldType
    {
        Integer = 1,
        Long = 2,
        String = 3,
        LargeString = 4,
        DateTime = 5,
        Decimal = 6,
        Guid = 7,
        Boolean = 8
    }
}

https://github.com/Orckestra/C1-CMS-Foundation/blob/1dfab411e5607d7c5e3acc7cd48874d28e6cd5e7/Composite/Data/PhysicalStoreFieldType.cs

resulted  - every time we have to convert:

`//playing with distance
    var latitude = 57.2957795130823D;

    var longitude = 39.75586574D;

    var coord = new GeoCoordinate(latitude, longitude);
    var nearest = locations.OrderBy(x => (new GeoCoordinate(Decimal.ToDouble(x.Latitude), Decimal.ToDouble(x.Longitude)).GetDistanceTo(coord)))
                           .First();`

**Comment by burningice2866** [comment]
You can convert your Double to Decimal without any worries since it has better precision than Double (while taking up a bit more space as well).

If your storing the data in SQL, consider simply going native with ie. Entity Framework since SQL has a coordinate datatype.
