### ISSUE TITLE
4.3: editor not functioning: relying on external composite.net resources

### ISSUE THREAD

**Issue by stephanedeuvaert** [Orckestra/C1-CMS-Foundation#475]
For example: http://c1console.composite.net/Composite/skins/system/tabboxes/vista/tab-sw.png

Do I need to upgrade to be able to edit my site?

**Comment by mawtex** [comment]
Nope - the only external content you should experience, is in the welcome dialog. Nothing in the editor should reference anything external (?)

**Comment by stephanedeuvaert** [comment]
Everything is loading except the content tab. I don't know how an error would cause images to attempt to get loaded from composite.net, but I have a console with around 10 images trying to load from composite.net.

**Comment by mawtex** [comment]
You can rule this out by editing  /Composite/web.config and set the appSetting "Composite.StartPage.Url" to "" (empty string).

My guess is that an upgrade is the way to go (or use another browser) - we've seen browser releases that break the visual editor (TinyMCE) and we've fixed that in later C1 releases.
