### ISSUE TITLE
Regarding FormBuilder

### ISSUE THREAD

**Issue by ai-fwd** [Orckestra/C1-CMS-Foundation#476]
I love the FormBuilder and the flexibility it brings however i'm not a big fan of the markup it generates, i need to change the CAPTCHA provider and I'd also like to add some extension points (i.e. have it trigger certain events i can subscribe to). 

I don't believe i'm able to make any of the changes i need since i don't have access to the source code. Is there a possibility of getting access to the source as part of the license?

**Comment by mawtex** [comment]
If we are thinking about the same [form builder](https://c1.orckestra.com/Add-ons/All/Orckestra.Forms.FormBuilder), then you have a **ton** of control on the markup. This part was very important in our design.

All fields are produced by Razor Functions, so you will find each field below ~/App_Data/Razor/Composite/Forms/FormBuilder/Fields.

To manage the form tag and any global form makrup, look at ~/App_Data/Razor/Composite/Forms/FormBuilder/Form.cshtml

See https://c1.orckestra.com/Add-ons/All/Orckestra.Forms.FormBuilder/UserManual/Form-Builder-Developer-Guide/Changing-the-HTML-or-behavior-of-existing-fields for documentation
