### ISSUE TITLE
The system gets non-responsive after a file upload in MS Edge

### ISSUE THREAD

**Issue by wwwysocki** [Orckestra/C1-CMS-Foundation#48]
**Repro**:
1. Use Microsoft Edge.
2. Media > Upload File
3. Select an image file and have it uploaded.
4. Wait for the file to appear in the tree and in the browser view.

**Expected**: Once the file appears in the console, you can continue to work.
**Actual**: The cursor gets into waiting mode.

**Comment by wwwysocki** [comment]
In some cases (still unclear which) it won't reproduce, so re-opened bu demoted to low severity.

Try this scenario:

1. Use Microsoft Edge.
2. Use a fresh installation.
3. Log in to the C1 Console (for the first time).
4. Media > Upload File
5. Select the file attached here (red_apple.jpg)
6. Wait for the file to appear in the tree and in the browser view.

**Expected**: Once the file appears in the console, you can continue to work.
**Actual**: The cursor gets into waiting mode.

Clicking elsewhere won't help, only ESCaping will.

In my experience, a few more uploads like this will cause this issue. Then it might be gone for good.

![red_apple](https://cloud.githubusercontent.com/assets/14821915/11467935/51c64bce-9754-11e5-95c7-d54ad0db2af6.jpg)

**Comment by mawtex** [comment]
Unable to reproduce a hang.
