### ISSUE TITLE
Feature Request: Turn on Scope Validation by default

### ISSUE THREAD

**Issue by burningice2866** [Orckestra/C1-CMS-Foundation#483]
As of May 10th, newer versions of the Microsoft Dependency Injection has turned on scope validation by default (https://github.com/aspnet/DependencyInjection/releases/tag/rel%2F2.0.0-preview1) which i believe would be the right thing to do in C1 as well as long as we're using version < 2.0.

This requires a simple change to this line https://github.com/Orckestra/C1-CMS-Foundation/blob/dev/Composite/Core/ServiceLocator.cs#L25, where `true` is passed to the `BuildServiceProvider` method.

I'd be happy to send a PR if you agree in making this change.

**Comment by mawtex** [comment]
Please do - optimal if you can run the nightwatch tests and check they pass okay.

**Comment by burningice2866** [comment]
Looking closer at the https://github.com/aspnet/DependencyInjection/issues/481 thread, it turns out they are only enabling Scope Validation when the application is running in Development Mode which i've updated my code to mimic by looking at the Debug Compilation Flag.

This makes sense since Scope Validation has a slight performance overhead and its mainly during development you want the extra checking to see if you messed up in you of your service registrations.

**Comment by burningice2866** [comment]
@mawtex ... and then what, something i'm missing here?

**Comment by burningice2866** [comment]
I suppose this can be closed.

**Comment by burningice2866** [comment]
Implemented in #484
