### ISSUE TITLE
Problem establishing WebSocket connection to server (using ActiveDirectory authentication)

### ISSUE THREAD

**Issue by ThisIsMeJKB** [Orckestra/C1-CMS-Foundation#487]
I installed the Orkestra.Search.LuceneNET package on my site and when I click the magnifying glass to go into the Search Perspective I get this error, **Problem establishing WebSocket connection to server** along with a message telling me the server may not support web sockets and directing me to a link in the help docs.

I was able to get to this work perfectly in my development environment on my local machine, but when attempting to run it on the server gets me that. I did follow the suggested link and verified that the WebSocket Protocol was/is installed and running but I'm still receiving this message. **ALSO**, when I was first installing  C1 on the server I got all green checkmarks at the first screen where it does all of server checks (and its my understanding, checking for sockets is an item on that list).

I'm running C1 v6.2 on Windows Server 2012 R2 using IIS 8.5

**Comment by burningice2866** [comment]
Have you checked the Server Log for any errors? WampSharp, which is driving the Websockets in C1, consists of quite a few assemblies and it easy to miss or two during deployment or get the versions mixed up which doesn't show up anywhere else than in the Server Log and as the behavior you're describing.

**Comment by ThisIsMeJKB** [comment]
I finally found the problem here.

To answer your question, I had checked the Server Log (both in C1 and the Event Logs on the server) but those weren't turning up anything.

I've been migrating several client sites over the past couple of months from very old legacy versions (4.x) to 6.2 and on my most recent migration, I was able to figure out what was going on here.

I am leveraging **ActiveDirectory authentication** (using the commercial plug-in) on these sites that have been giving me issues and because of that I noticed that when the Search perspective first attempts to load it will make an ajax request to **/api/Renderers** (or something close to that) but that request is rejected by the server, saying that it's **"Not Authorized"**.

Activating the ActiveDirectory plugin is usually one of the very last things I do before handing the site back over to the client and I've noticed that the Search perspective works great before I install that plugin, but once that plugin is installed it stops working and gives me that error.

Thoughts?

**Comment by mawtex** [comment]
Sounds like we have a bug here :/ Is this an issue across browsers?

**Comment by ThisIsMeJKB** [comment]
Doesn't appear to be.

I've tried it in Chrome and MS Edge.

Worked in Edge but did not work in Chrome.

**Comment by mawtex** [comment]
Reading https://bugs.chromium.org/p/chromium/issues/detail?id=423609 it looks like there is an issue with windows auth and web sockets and chrome - one of the last comments indicate that auth fail when going by IP, while it would work when using a fully qualified domain name. Does this info help?

**Comment by ThisIsMeJKB** [comment]
Hey, sorry for the delayed response on this. And thanks for finding that thread.

I did take a look at the comment you mentioned at the bottom and it looks like we have very similar use cases: the installation in question is being used behind a company firewall as an intranet for the business (which is why they wanted ActiveDirectory authentication for the CMS). But the thread is not helpful for me (assuming I correctly understand what was being said) because the intranet is currently being accessed through a fully qualified domain, **intranet.[domain].[tld]**.

Just to make sure I'm absolutely clear on the hang-up, the issue lies between Google Chrome and how its handling WebSockets with Windows Authentication and has nothing to do with the C1 CMS, right?

And if that is the case, are there any workarounds, outside of using a different browser (haha)?

Thanks for you help on this!
