### ISSUE TITLE
Multiple versions of the same content

### ISSUE THREAD

**Issue by ThisIsMeJKB** [Orckestra/C1-CMS-Foundation#496]
It's my understanding that versions were introduced somewhere in v5.x, I just upgraded a site from v4.3 and v6.2 and now whenever a page is edited I notice multiple versions of that page (and pageContent) are showing up in the database.

Even though there are now 2 versions of that page it still loads fine on the public facing website, though it loads the older version while viewing the page in C1 I see the new version.

I also notice that when I continue to edit that page the newer version of the page is what gets updated (in the DB) and the older version never gets touched.

What might be causing the duplication? Is there something that I didn't migrate/upgrade properly while doing my upgrade?

Thanks!

**Comment by ThisIsMeJKB** [comment]
What code gets executed when the "Save" or "Save and Publish" button is clicked on a Page?

If I know that I can probably step through that process and figure out what is causing the duplication.

**Comment by burningice2866** [comment]
https://github.com/Orckestra/C1-CMS-Foundation/blob/dev/Composite.Workflows/Plugins/Elements/ElementProviders/PageElementProvider/EditPageWorkflow.cs#L304

**Comment by ThisIsMeJKB** [comment]
I was able to figure out what was causing me problems. It was an oversight in my data migration script.

Thanks for the link!
