### ISSUE TITLE
[Chrome] Input fields loosing focus if login/password information is preserved in browser

### ISSUE THREAD

**Issue by napernik** [Orckestra/C1-CMS-Foundation#504]
Repro:
1) Use Chrome version 63.x
2) Log into C1 console, choose to remember the login/password information
3) Click on "Add page" in с1 console, or edit any C1 page
4) Try editing one of the fields

Result: the field loses focus every 5 seconds, making editing inputs rather difficult.

Workaround is either to remove remembered password in Chrome or to use the incognito mode.

**Comment by neexite** [comment]
**Manual fix for this issue:**

1) Open for edit ~/Composite/scripts/compressed/top.js
2) Insert code in the new lines:
`"undefined"!=typeof KickStart&&"undefined"!=typeof EventBroadcaster&&EventBroadcaster.subscribe&&/Chrome/.test(navigator.userAgent)&&(KickStart.subscribeToRemoveObsoluteDecks=function(){this.isSubscribedToRemoveObsoluteDecks||(this.isSubscribedToRemoveObsoluteDecks=!0,EventBroadcaster.subscribe(BroadcastMessages.APPLICATION_LOGIN,{handleBroadcast:function(){try{if("undefined"!=typeof top&&top.bindingMap&&"undefined"!=typeof DocumentManager&&DocumentManager.detachBindings)for(var e=["logindeck","changepassworddeck"],t=0;t<e.length;t++)obsoletedDeckName=e[t],top.bindingMap[obsoletedDeckName]&&(obsoletedDeck=top.bindingMap[obsoletedDeckName],obsoletedDeck&&obsoletedDeck.bindingElement&&(DocumentManager.detachBindings(obsoletedDeck.bindingElement,!0),obsoletedDeck.bindingElement.innerHTML=""))}catch(e){}}}))},KickStart.subscribeToRemoveObsoluteDecks()); `

**Comment by neexite** [comment]
**Manual fix for this issue:**

1) Open for edit ~/Composite/scripts/compressed/top.js
2) Insert code in the new lines:
`"undefined"!=typeof KickStart&&"undefined"!=typeof EventBroadcaster&&EventBroadcaster.subscribe&&/Chrome/.test(navigator.userAgent)&&(KickStart.subscribeToRemoveObsoluteDecks=function(){this.isSubscribedToRemoveObsoluteDecks||(this.isSubscribedToRemoveObsoluteDecks=!0,EventBroadcaster.subscribe(BroadcastMessages.APPLICATION_LOGIN,{handleBroadcast:function(){try{if("undefined"!=typeof top&&top.bindingMap&&"undefined"!=typeof DocumentManager&&DocumentManager.detachBindings)for(var e=["logindeck","changepassworddeck"],t=0;t<e.length;t++)obsoletedDeckName=e[t],top.bindingMap[obsoletedDeckName]&&(obsoletedDeck=top.bindingMap[obsoletedDeckName],obsoletedDeck&&obsoletedDeck.bindingElement&&(DocumentManager.detachBindings(obsoletedDeck.bindingElement,!0),obsoletedDeck.bindingElement.innerHTML=""))}catch(e){}}}))},KickStart.subscribeToRemoveObsoluteDecks()); `

**Comment by burningice2866** [comment]
Since a new commit has been made and reading this issue, is the fix mentioned by @neexite still complete?

**Comment by napernik** [comment]
Yes, the other commit is fixing the Nightwatch tests that we're using, which are not a part of deployment.
