### ISSUE TITLE
[Chrome 63] Function call editor - text is not visible in the second column input fields.

### ISSUE THREAD

**Issue by napernik** [Orckestra/C1-CMS-Foundation#506]
Repro:
1) Create a razor function with 2 text fields

```
@inherits RazorFunction

@functions {
    public override string FunctionDescription { get { return "Text overflow bug"; } }

    [FunctionParameter(Label = "Left", DefaultValue = null)]
    public string LeftText { get; set; }

    [FunctionParameter(Label = "Right", DefaultValue = null)]
    public string RightText { get; set; }
}

<html xmlns="http://www.w3.org/1999/xhtml" xmlns:f="http://www.composite.net/ns/function/1.0">
<head />
<body />
</html>

```

2) Insert the function on a C1 page
3) Try to put more text in right text field than fits into the text box:
Expected: the text is still visible
Actual: the text is not rendered at all

![image](https://user-images.githubusercontent.com/1391705/34215488-bf3dbcf4-e5a5-11e7-942b-faeb8131e869.png)

**Comment by neexite** [comment]
https://jsfiddle.net/93od6L06/ simple Chrome issue

**Comment by neexite** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=796604 Reported bug to Chrome

**Comment by neexite** [comment]
[hotfix506.zip](https://github.com/Orckestra/C1-CMS-Foundation/files/1579086/hotfix506.zip)

**Comment by neexite** [comment]
Customers with a [C1 CMS Service Plan](https://c1.orckestra.com/Products/Plans#tab_service_plans) (developer, business or premium) can now install a hotfix that solves this issue.

**Install steps for hotfix:**
1) Launch the CMS Console
2) On the `System` perspective, browse down `Packages`, `Available Packages`, `Composite.Updates`
3) Install the package `Composite.Updates.HotFix506`

**The hotfix requires browser cache to be flushed** - for browsers accessing the CMS console to edit content, use the browsers cache flush option (ctrl+shift+del - "Clear cache"  / "Clear cached files" depending on browser).

**Comment by neexite** [comment]
**Manual fix for this issue:**

1) Open for edit ~/Composite/styles/styles.min.css
2) Add the following line to the end of the file:


`@media screen and (-webkit-min-device-pixel-ratio:0) and (min-resolution:0.001dpcm){ui|dialogpage.functionview-basic ui|fieldgroup ui|fielddata ui|datainput ui|box{overflow:visible;padding:0 2px}ui|dialogpage.functionview-basic ui|fieldgroup ui|fielddata ui|datainput ui|box input{padding-left:5px}ui|editorpage ui|fields ui|fielddata ui|datainput ui|box{overflow:visible;padding:0 2px}ui|editorpage ui|fields ui|fielddata ui|datainput ui|box input{padding-left:5px}}`
