### ISSUE TITLE
C1 CMS image running in Azure App Service Web App 

### ISSUE THREAD

**Issue by motasem13** [Orckestra/C1-CMS-Foundation#509]
Hello, 
i have an issue running C1 cms in azure app service which will end up throwing 5XX http errors after a while, Azure sandbox does not support PhantomJS,
note : Other scenarios that are not supported:
• PhantomJS/Selenium: tries to connect to local address, and also uses GDI+.” 

I have checked C1 CMS documentation and it seems that The function previews are generated by using a PhantomJS process running in the background.
https://docs.c1.orckestra.com/Console/Function-Previews

turning off this feature will resolve this issue, by default this feature is turned on, i guess it would be better to turn it off to avoid such issue in the future.

**Comment by burningice2866** [comment]
Perhaps we should consider adding a installation-step which checks if PhantomJS can be run and if not, then automatically disable Function Preview.

This will of course not help in the situation where you install C1 locally and then deploy, but if you install C1 directly on the Azure Web Service, then you would avoid such an issue.
