### ISSUE TITLE
Redirected to the default tab when inserting an image etc in the editor

### ISSUE THREAD

**Issue by wwwysocki** [Orckestra/C1-CMS-Foundation#517]
**Summary**: If you insert an image, link, function etc in both Visual and Source Editors and do something in the Properties popup window as well (for example, Crop Image, Upload File, etc) and when done, you are redirected to the default tab ("Content") from the editor with the page open.

**Repro**:

1. Edit a page.
2. Insert an image and wait for the "Select Image" window pops up over "Insert Image".
3. Do something in this window using the buttons, for example, crop an image or upload an image.
4. Select an image (if not yet) and click OK in "Select Image", then in "Insert Image".

**Expected**: You are back in the editor (with the image inserted)
**Actual**: You are forced onto the default "Content" tab.

**Notes**: 

* Affects other insert windows, for example, "Insert Link"
* Reproduced in both Visual Editor and Source Editor
* Affects all the browsers

**Workaround**:

Unknown at the moment but you can always get back to the edited page by clicking the respective tab.

**Comment by mawtex** [comment]
This is what happen: When clicking toolbar buttons in a popup, the click event "bubble through" the popup and also invoke buttons in the underlying layer. For example, if you move the above mentioned popup so the image crop button is above the "Preview" tab and you then click the crop button, you will see the preview tab invoked.

**Comment by wwwysocki** [comment]
Partly duplicated in https://github.com/Orckestra/C1-CMS-Foundation/issues/574

**Comment by wwwysocki** [comment]
Verified on 20180621.1 (dev)
