### ISSUE TITLE
[Chrome] Can't enter the Type Name etc when creating a data type

### ISSUE THREAD

**Issue by wwwysocki** [Orckestra/C1-CMS-Foundation#526]
**Repro**:

1. Use Chrome
2. Use it on a display with the screen resolution of 1920x1080 (14'') or 1950x1080 (>14'' but resized to be a bit smaller). **Important!** Make sure the fields are still laid out in two columns.
3. Data > Global Data Type > Add Data Type
4. Enter the Title
5. Try and enter the Type name, Type namespace, Short URL name

**Expected**: You can type in values in these fields
**Actual**: You can't type in values in these fields. You can't place the cursor in them. 

**Workaround**:

Use the screen resolution of 1920x1080 with the >14'' diagonal size, or experiment with the browser window sizes.

<img width="853" alt="chrome-global-datatype-typename-field" src="https://user-images.githubusercontent.com/14821915/35338436-9f4d00e8-0126-11e8-87e1-5075e69b55f5.png">

**Comment by mawtex** [comment]
For info, I'm unable to reproduce this. Using Chrome 63.0.3239.132 (Windows 10).

**Comment by wwwysocki** [comment]
Changed the severity to "Low" for now, since I can't reproduce it either on some other PC. Will investigate it.

**Comment by wwwysocki** [comment]
Did the investigation. The issue is reproducible on a specific screen resolution - the steps are updated accordingly. I am keeping the low severity but please do change it if you see it more common than my case.

My case:

I have two monitors, both 1920x1080, the same computer. The issue is reproducible only in one of them :). It looks like one of them is actually a little bit smaller than the other. The "little bit smaller" screen causes the problem.

**Comment by neexite** [comment]
Reproducible on the setting: 1920x1080 + 150% Scale and Layout(on both 15" and 14")
150% Scale and Layout is displayed as "Recommended" on my laptop.

**Comment by wwwysocki** [comment]
The same issue occurs in other places. For example, if you have a publishable data type, try and set a publish/unpublish date (provided the Publication Settings group appears in Column 2). The selected date/time won't appear in the field unless you resize the window or view it in a different browser.

**Comment by wwwysocki** [comment]
Please upgrade your Chrome browser to Version 64.0.3282.119 or later. 
The issue is no longer reproducible in this Chrome version.
