### ISSUE TITLE
[XSLT Functions] Changes in the template do not appear in the Preview Output

### ISSUE THREAD

**Issue by wwwysocki** [Orckestra/C1-CMS-Foundation#534]
**Repro**:

1. Create or edit an XSLT function.
2. See what the "Output" area shows on the "Preview" tab.
3. Change something in the template so that the output would change, too.
4. See again what the "Output" area shows on the "Preview" tab.

**Tip**: On a newly created function, you can delete the default content within the < body > element for Step 3.

**Workaround**:

Save, close and re-open the function.

<img width="477" alt="xslt-functions-preview-output" src="https://user-images.githubusercontent.com/14821915/35391058-2f7589e6-01e6-11e8-8df0-0d4ba34946a8.png">

**Comment by mawtex** [comment]
This seem to have been fixed when #561 was fixed. Repro is no longer showing the issue
