### ISSUE TITLE
Custom 404 page resolution does not take language specified in URL into account

### ISSUE THREAD

**Issue by napernik** [Orckestra/C1-CMS-Foundation#535]
Repro:
1) Have a website with at least 2 languages
2) Create a hostname binding for a website specify a 404 page
3) Localize the website and the 404 page
4) Access the following urls:
http://<hostname>/language1/<not existing page>
http://<hostname>/language2/<not existing page>

Expected: the 404 page will be rendered in the respective language
Actual: the 404 page is only shown in the same language which is specified as a default one in the hostname binding.

**Comment by wwwysocki** [comment]
Verified on 20180125.7
