### ISSUE TITLE
Losing the cursor when typing

### ISSUE THREAD

**Issue by kcthink** [Orckestra/C1-CMS-Foundation#545]
When I type in any field in the CMS, the cursor seems to dissapear and I have to click back in the field to be able to continue writing. I've checked all of the hardware components and the problem seems to be the CMS. This happens on Chrome, IE and Edge (firefox and Safari not tested). This happens no matter the field, the page or the component. It happens constantly and only in this CMS. 
[ScreenRecorderProject4.zip](https://github.com/Orckestra/C1-CMS-Foundation/files/1741805/ScreenRecorderProject4.zip)

**Comment by napernik** [comment]
It looks like this bug https://github.com/Orckestra/C1-CMS-Foundation/issues/504

Try opening the CMS in Chrome in incognito mode, if it helps, the fix is described in the comments in the link above.

**Comment by napernik** [comment]
Likely fixed in the latest release, closing for now.
