### ISSUE TITLE
2nd, 3rd etc. page preview will show data from 1st

### ISSUE THREAD

**Issue by mawtex** [Orckestra/C1-CMS-Foundation#561]
Repro:

1. Edit a page, make a content change, preview the page
2. In the same edit session, make another content change and preview the page

Expected: the second preview reflect the second content change
Actual: the browser will keep posting back content from step 1, and you keep seeing the same step 1 content change.

**Comment by jaouw-estate** [comment]
is there any update on this issue allready ?
