### ISSUE TITLE
using asych deferred js directly into editor window is not supported 

### ISSUE THREAD

**Issue by mmillendorfer** [Orckestra/C1-CMS-Foundation#568]
e.g.
<script src="https://apis.google.com/js/platform.js" async defer></script>[...]

is there a workaround to put the code directly into the editor?

cheers
Markus

**Comment by burningice2866** [comment]
Technical explanation would be that HTML5 introduced the concept of [boolean attributes](http://w3c.github.io/html/infrastructure.html#sec-boolean-attributes), where the presence of an attribute represents true and the absence represents false.

For boolean attributes the value of the attribute must either be empty or the same as the name of the attribute.

That means that for ie. async, **_both_** `async="async"` and just `async` is valid in HTML5, but only the former is valid in xhtml.
