### ISSUE TITLE
InternalUrl taking a while to "map"

### ISSUE THREAD

**Issue by ThisIsMeJKB** [Orckestra/C1-CMS-Foundation#570]
I'm using v6.3 running in a Windows 2012 environment.

I just created a new datatype, via code, to represent a new section of a site I'm maintaining but for some reason, it looks like the InternalUrl configuration does not immediately map for the instances of that data type.

What I specifically mean by "does not immediately map" is that when the data type is added and becomes visible on the website, I will attempt to click a link to that page and instead of getting the fully resolved relative path (so that it takes me to the page) I get the actual InternalUrl, **/data([GUID])**.

I'm using the DefaultUrlMapper and I'm assuming there is some kind of Caching interference going on with the data provider as per the reason I mentioned previously and after an undetermined amount of time OR I go into the C1 admin and "Restart Server" it will work. Note, I do have the "Caching" attribute set on this data type.

Any thoughts on what could be causing this and how I could go about addressing. This issue is holding up the launch of this new section of my client's site.

**Comment by napernik** [comment]
Hi @ThisIsMeJKB 

This is by design, you can register an "internal url mapping" in a startup handler, please check the code example here:

https://docs.c1.orckestra.com/Data/Linking-to-Data-Items/Internal-Data-Link-Formats#Internal-Linking-for-Static-Data-Types

**Comment by mawtex** [comment]
@ThisIsMeJKB can you provide us with some details on your setup? What type of data type are you using (global vs page folder) and what is the signature of the function rendering it on your page?
