### ISSUE TITLE
UX Bug: using link function in content editor

### ISSUE THREAD

**Issue by djalfe** [Orckestra/C1-CMS-Foundation#574]
Hey there, i think something not right in the way you make a link in content area

if you click choose "Media archive" in link selector and make a new folder, then the folder is made in the first folder and not in the root at "Media Archive".
if you choose to upload a media through link selector, then the content page you are editing is loosing focus.
I have made a video, hope it will help understand what trying to tell :-)
https://www.screencast.com/t/TLOwyo25VyI

This test i made with newly download version of C1 CMS Build no. 6.4.6639.31891

**Comment by mawtex** [comment]
Two issues shown in the video:

1) Selecting a media folder (when last view was a C1 Page) will auto select first child folder (if any). 
2) The content perspective browser gets focus (editor loses focus) after link selector dialog has been active.

**Comment by djalfe** [comment]
Thanks that works, have just tried it out on at developer version.
Next would be a new release, because this bug is a "pain in the a.." for editors worldwide.

**Comment by wwwysocki** [comment]
Verified on 20180621.1 (dev)
