### ISSUE TITLE
When a page is deleted, the focus moves to the "invisible" root node

### ISSUE THREAD

**Issue by wwwysocki** [Orckestra/C1-CMS-Foundation#581]
**Repro**:

1. In the Content perspective, select a page (a child page)
2. Delete it
3. Check for the focus in the tree
4. Check the preview

**Expected**:

Step 3: The focus goes 1 level up (to the parent page or node)
Step 4: The preview shows the contents of the parent page/node [as a result]

**Actual**:

Step 3: The focus goes to the root node, which is actually not present in the tree
Step 4: The preview shows 3 nodes (default Venus): Websites, Website Items, Form Submissions 

![chrome_2018-06-21_13-37-54](https://user-images.githubusercontent.com/14821915/41714252-557a433a-7558-11e8-986a-243fb89afb1e.png)

**Comment by mawtex** [comment]
> Expected:
> Step 3: The focus goes 1 level up (to the parent page or node)
> Step 4: The preview shows the contents of the parent page/node [as a result]

That would be real nice!

**Comment by neexite** [comment]
Server does not send any information to select parent node (only refresh parent)

**Comment by wwwysocki** [comment]
Verified on 20180629.1 (dev)
