### ISSUE TITLE
WAWS (Azure AppServices) are not supported out-of-the-box as hosts for C1 CMS

### ISSUE THREAD

**Issue by wwwysocki** [Orckestra/C1-CMS-Foundation#582]
**Note**:

App Services have the WebSockets disabled by default.
(When manually enabled in Azure, it works OK.
If we can't do anything on our side, this might be closed as a "by design" issue)

**Repro**:

1. Upload and publish a non-initialized C1 CMS as an Azure Website (AppService), for example, from WebMatrix
2. Run the C1 CMS wizard

**Expected**: All setup options validate
**Actual**: WebSockets support fails

![chrome_2018-06-21_14-00-33](https://user-images.githubusercontent.com/14821915/41715334-c0d69c02-755b-11e8-9a99-477c2c4609ee.png)

**Workaround**:

![2018-06-21_12-43-39-](https://user-images.githubusercontent.com/14821915/41715395-f5ba65ac-755b-11e8-93a0-5cc0e9281ab8.png)

**Comment by mawtex** [comment]
Clicking "Read more" on the Welcome check screen give you the work around, which is nice.

Practically, we can't configure the WAWS WebSocket setting as part of the C1 setup, we need the website to be configured on a few points. A system requirement, if you will. I will close this.
