### ISSUE TITLE
Adding a new perspective not working (?)

### ISSUE THREAD

**Issue by wwwysocki** [Orckestra/C1-CMS-Foundation#592]
**Question**:

Is the feature of adding custom perspective via Composite.config working? Are the steps suggested below enough to make it work?

**Repro**:

Scenario 1:

1. Edit `~\App_Data\Composite\Composite.config`
2. Locate the Search Perspective element.
3. Copy and paste it below
4. Make changes in the copied element (`name`, `tags`, `label `etc) - See **Example 1** below
5. Save the changes
6. Clear the browser cache, restart the server, reload the console
7. Check for a new perspective

Scenario 2:

1. Edit `~\App_Data\Composite\Composite.config`
2. Add an example from https://github.com/Orckestra/C1-CMS-Foundation/releases/tag/v6.0 with a different name (?) where necessary - See **Example 2** below.
3. Save the changes
4. Clear the browser cache, restart the server, reload the console
5. Check for a new perspective

**Expected**:

A new perspective shows up

**Actual**:

No new perspective shows up

**Example 1**:

```
<add name="ToolsPerspective" tag="Tools" label="Tools" closeFolderIconName="Composite.Icons.generic-search" type="Composite.Plugins.Elements.ElementProviders.VirtualElementProvider.PlaceholderVirtualElement, Composite" path="${root}/console/index.html?pageId=search" IsTool="true">
  <Elements />
</add>
```

**Example 2**:

```
<add name="SearchPerspective2" tag="Search" label="Search" closeFolderIconName="Composite.Icons.generic-search" type="Composite.Plugins.Elements.ElementProviders.VirtualElementProvider.PlaceholderVirtualElement, Composite" path="${root}/console/index.html?pageId=search" IsTool="true">
  <Elements />
</add>
```

**Comment by burningice2866** [comment]
Have you checked permissions for your C1 user/group? Default but not-obvious behavior is that no one has permissions to see newly added perspectives and that would have to be set explicitly afterwards.

**Comment by wwwysocki** [comment]
Thank you, @burningice2866 . That was it! Setting the permissions helped

**Comment by burningice2866** [comment]
IMO its maybe not a but, but certainly not intuitive, neither stated in any documentation. I've spent days on this as well the first few times i tried making my own perspectives so i would say something should be done to make it more friction-less.

Maybe a dialog at first Console Login after a new perspective has been added prompting who should have access to it.
