### ISSUE TITLE
Aligning possible lengths of Page Title, MenuTitle and UrlTitle

### ISSUE THREAD

**Issue by burningice2866** [Orckestra/C1-CMS-Foundation#604]
As of now, the Title, MenuTitle and UrlTitle of a page all have different max values

 - Title: 255 chars
 - MenuTitle: 64 chars
 - UrlTitle: 192 chars

While its hard to say what the optimal length is, they should at least be somewhat aligned so my proposal is to adjust the length of MenuTitle to 192 chars as well since its value often will be the same as UrlTitle, where the latter is just formatted in a url friendly way.

**Comment by mawtex** [comment]
Out of curiosity: Is this suggestion driven by a use case that failed due to the different lengths, or were you looking at IPage.cs and the different numbers caught your eye?

**Comment by burningice2866** [comment]
The former and the reply to the customer was going to be "64 chars is the overall limitation for Page titles", but then i stumbled upon this inconsistency.

If anything, it should be the UrlTItle and not MenuTitle that should be limited in length.

**Comment by burningice2866** [comment]
Will do.
