### ISSUE TITLE
Rendering Razor Functions in MVC Controller Actions

### ISSUE THREAD

**Issue by peterpde** [Orckestra/C1-CMS-Foundation#609]
I am wanting to implement some hybrid client side app server side scenarios.  One of the things I was hoping to accomplish was being able to render certain Razor Functions or XHTML field content  server side and pass the output back to some client side java code in the form of json for use in client side binding.

Is this at all possible?  Something like...

`var myVM = this.connection<news>().Take(10).Select(s => new vm { id = s.Id, renderedContent = xhtmlContentRenderer.Render(s.NewsXhtmlContent)}).ToList();`
`var json = JasonConvert.Serialize(myVm);`

Thanks

**Comment by burningice2866** [comment]
You cab execute Functions and prepare its result for output like this https://github.com/burningice2866/CompositeC1Contrib/blob/master/FunctionRoutes/FunctionRouteHandler.cs

**Comment by peterpde** [comment]
That looks great.  Thank you.
