### ISSUE TITLE
API to refresh specific cache entries

### ISSUE THREAD

**Issue by ai-fwd** [Orckestra/C1-CMS-Foundation#623]
We have a few manual scripts that hit the DB directly to perform some workflows. When we update certain tables these changes aren't reflected on the website because of the C1 cache. 

I remember there being some discussions on the old forums about some manual work that had to happen but can't seem to find it anywhere and also was hoping that maybe some improvements had been made in this area.

Ideally we'd like to be remove specific entries in the cache vs. dumping the entire cache.

Thanks.

**Comment by mawtex** [comment]
To get C1 to flush data of a specific type, you can fire a OnStoreChanged event, see http://api.composite.net/html/E_Composite_Data_DataEvents_1_OnStoreChanged.htm 

> Ideally we'd like to be remove specific entries in the cache vs. dumping the entire cache.

C1 does not support flushing single data items - all data of a given type will be refreshed. Sorry :/ If there is a massive amount of data and flush happen often enough, disabling caching for the type might be a fix. Or - if all else fail - implement your own [data provider](https://docs.c1.orckestra.com/Data/CustomDataProviders).

**Comment by burningice2866** [comment]
@mawtex How exactly did you have in mind one would go about and fire such event?

Looking at DataEventSystemFacade, it doesn't look like there are any plublic methods for firing events.

**Comment by mawtex** [comment]
True, something like the below is needed for v6.3.

```
MethodInfo DataEventSystemFacade_FireExternalStoreChangeEvent = typeof(DataEventSystemFacade)
                .GetMethod("FireExternalStoreChangedEvent", 
                BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Static, null,
                new[] { typeof(Type), typeof(PublicationScope), typeof(CultureInfo) }, null); ;

DataEventSystemFacade_FireExternalStoreChangeEvent.Invoke(null, new object[] { type, publicationScope, culture });
```

**Comment by burningice2866** [comment]
Sounds like a change to the API is called for? Would you accept a PR on this?

**Comment by ai-fwd** [comment]
@mawtex can you provide some insight on why something like IHostnameBinding (CachingType.Full) and IPage (CachingType.Full) seem to use two different approaches to caching?

IHostnameBinding seems to be managed via the DataCachingFacade (although i'm unable to locate a call to RemoveData for this specific data type).

IPage seems to managed by PageManager with some static Cache objects. In this case it does seem to support row level removal via the DataEventArgs that are passed in. 

Can idea on why the different implementations?

**Comment by burningice2866** [comment]
@napernik So `[CachingAttribute(CachingType.Full)]` has different meaning on Xml vs Sql dataprovider? On Sql its just ignored?

**Comment by napernik** [comment]
I updated my comment to make it a bit less ambiguous

**Comment by burningice2866** [comment]
So to take the example with `IPagePlaceholderContent `, since it has the `CachingAttribute(CachingType.Full)]` configured, when on Sql, all its records will all be loaded into memory when you query the datatype or not?

**Comment by napernik** [comment]
It is a good question. The answer is - it depends on how you query it:

If you use **DataConnection.Get<IPagePlaceholderContent>()** or **DataFacade.GetData<IPagePlaceholderContent>()** - the first time you call it, the whole data table will be loaded into memory.

If you use the hidden gem, which is **DataFacade.GetData<IPagePlaceholderContent>(useCaching: false)**, then it will not load it into memory. If you check **PageManager** - that's exactly the call that is used.

Answering the question that it leads to - yes, it makes sense to remove the caching attribute from the **IPagePlaceholderContent** specifically, as in a way it is a hidden performance mine one can accidentally step on when building a site with lots of content. Probably even adding an overload to **DataConnect.Get<>** as well.

**Comment by ai-fwd** [comment]
@napernik Thanks for the explanations. Can you confirm that PageManager is a one off and not a pattern used elsewhere in the C1 code base. I see no backing interface or way to create a DataManager<T> that can be plugged in for other datatypes -- specifically IHostnameBinding. Is that correct?
