### ISSUE TITLE
DefaultPageUrlProvider uses wrong encoding for path which causes double escaping

### ISSUE THREAD

**Issue by ai-fwd** [Orckestra/C1-CMS-Foundation#624]
I search the commits and bugs for anything on this but I don't see any changes that have fixed it in the latest version (I'm using 6.3 so let me know if it has been fixed).

[this line](https://github.com/Orckestra/C1-CMS-Foundation/blob/546737d705a0b65170f6a5a84fa12bd74e486086/Composite/Plugins/Routing/Pages/DefaultPageUrlProvider.cs#L886) ends up using HttpUtility.UrlEncode and i believe it should use UrlPathEncode instead. 

I'm seeing this cause an issue in something like this:

`<a href="~/page(@pageId)/properly%20encoded">...</a>`

It ends up spitting out "properly+encoded" which then causes an error when trying to access that link with 

**The request filtering module is configured to deny a request that contains a double escape sequence.**

Based on MSFT guidance:

> You can encode a URL using with the UrlEncode method or the UrlPathEncode method. However, the methods return different results. The UrlEncode method converts each space character to a plus character (+). The UrlPathEncode method converts each space character into the string "%20", which represents a space in hexadecimal notation. Use the UrlPathEncode method when you encode the path portion of a URL in order to guarantee a consistent decoded URL, regardless of which platform or browser performs the decoding.

More here: http://msdn.microsoft.com/en-us/library/4fkewx0t(v=vs.110).aspx

Let me know if i'm wrong...

**Comment by napernik** [comment]
Thank you for reporting the issue and providing a fix
