### ISSUE TITLE
Why does DefaultPageUrlProvider maintain an internal copy of IHostnameBindings?

### ISSUE THREAD

**Issue by ai-fwd** [Orckestra/C1-CMS-Foundation#632]
Curious why [this](https://github.com/Orckestra/C1-CMS-Foundation/blob/8763abc877880a6974d1f9f1d376831134a2df0b/Composite/Plugins/Routing/Pages/DefaultPageUrlProvider.cs#L70) exists when it could instead just return DataFacade.GetData<IHostnameBinding>().ToList(). 

Considering the fact that the class itself is internal and IHostnameBinding is Caching(CachingType.Full) I don't think there is a performance hit since we know the type is already loaded into memory.

Is there a specific reason for it or would you accept a PR on this to simplify it?

**Comment by mawtex** [comment]
I ran a quick test, querying 10000 times (code below - I had to make DefaultPageUrlProvider.GetHostnameBindings() public):

Data, IQueryable: 21030 ms
Data, Enumerable: 204 ms
Cached way: 3 ms

For 10000 reads the difference between 204 ms and 3 ms is negligent so you could simplify things. On the other hand this query would be hit on each page request though, so squeezing all perf gains out of it could make sense. So I'd keep things as is.

Btw the reason the IQueryable way is slower here is that .NET will compile your LINQ query as an expression tree (more abstract structure), which can end up with data providers to further query stores (like transforming the query into a real SQL query). In those steps there is compilation steps involved. The Enumerable approach will skip that step and pull all raw data, leaving LINQ to the caller and here the query can be fully compiled. 

```
@using Composite.Data;
@using Composite.Data.Types;
@using System.Linq;
@using Composite.Plugins.Routing.Pages;
@using System.Diagnostics;

<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
	@{
		using (var connection = new DataConnection())
		{
			Stopwatch sw = new Stopwatch();

			sw.Start();
			for (int i = 0; i < 10000; i++)
			{
				var c = connection.Get<IHostnameBinding>().Where(f => f.Hostname == "localhost").Count();
			}
			sw.Stop();
			<div>Data, IQueryable: @sw.ElapsedMilliseconds ms</div>
			sw.Reset();
			sw.Start();
			for (int i = 0; i < 10000; i++)
			{
				var c = connection.Get<IHostnameBinding>().AsEnumerable().Where(f => f.Hostname == "localhost").Count();
			}
			sw.Stop();
			<div>Data, Enumerable: @sw.ElapsedMilliseconds ms</div>
			sw.Reset();
			sw.Start();

			for (int i = 0; i < 10000; i++)
			{
				var c = DefaultPageUrlProvider.GetHostnameBindings().Where(f => f.Hostname == "localhost").Count();
			}
			sw.Stop();
			<div>Cached way: @sw.ElapsedMilliseconds ms</div>

		}
	}
</body>
</html>
```
