### ISSUE TITLE
SetupService.asmx doesn't have to be present for C1 console to load

### ISSUE THREAD

**Issue by napernik** [Orckestra/C1-CMS-Foundation#633]
The setup service isn't used by the console after it is initialized, but the console doesn't start if the file is removed.

\Composite\services\Setup\SetupService.asmx

Since the file isn't needed after installation, it should be allowed to remove the file manually after a deployment, and/or it should be removed by the setup wizard automatically.

**Comment by mawtex** [comment]
Don't remove the file - there is no reason do to so.

**Comment by burningice2866** [comment]
Is actually possible to execute commands againts the service after a site has been published? Service doesn't seem to be secured.

**Comment by mawtex** [comment]
> Is actually possible to execute commands againts the service after a site has been published? 

Nope, it goes passive once setup has completed.
