### ISSUE TITLE
Is it possible to set explicit permissions on a parent that is not inherited by child?

### ISSUE THREAD

**Issue by ai-fwd** [Orckestra/C1-CMS-Foundation#643]
Scenario #1: User has permissions to Read, Add, Edit, Delete, Approve, Publish a website/subsite and should have the freedom to perform all those actions on all sub-pages (children) but should not be able to delete or unpublish the website/subsite (parent). 

Scenario #2: User has permissions to Read, Add, Edit, Delete a Media Folder and should have the freedom to perform all those actions on all media files (children) but should not be able to delete the root folder (parent).

Currently when setting these permissions through the console the permissions are inherited which is the existing design. I'm wondering, is there is anything in the DataEntityToken that would allow me to manually create a DataEntityToken that is only applied to the parent?

**Comment by mawtex** [comment]
> Is it possible to set explicit permissions on a parent that is not inherited by child?

No, sorry. The closest you can get to this is to define permissions for the root and then overriding on each child - which do not satisfy your scenarios.
