### ISSUE TITLE
[Bug] Sequence can be empty when inserting the first page using AlphabeticPageInsertPosition

### ISSUE THREAD

**Issue by ai-fwd** [Orckestra/C1-CMS-Foundation#644]
https://github.com/Orckestra/C1-CMS-Foundation/blob/b78aeaaa75e0ed3e448115121a4f63e75688a2f5/Composite/Data/Types/PageInsertPosition.cs#L121

I've fixed this locally with minimal code impact by changing L92 to:
`int targetLocalOrdering = pageStructures.Any() ? -1 : 0;`

I don't think this requires a PR but let me know - or if the scenario is invalid. I'm scripting a site from scratch.

**Comment by mawtex** [comment]
Thanks, it's a good and defensive fix and I added it.

About a repro: In the UI, when adding a page, the 'alphabetic ordering' option will only show up if there is at least one page to begin with - so this issue will not surface in normal intended UI usage.
