### ISSUE TITLE
[BUG] FormBuilder - multiple forms on one page

### ISSUE THREAD

**Issue by ai-fwd** [Orckestra/C1-CMS-Foundation#647]
This may have been fixed since I likely don't have the updated FormBuilder bits but in Form.js on L60 you have:

`if (!$("form.formbuilder").valid()) {
            event.preventDefault();
        }`

This should be changed to:

`if (!$(this).valid()) {
            event.preventDefault();
        }`

Otherwise the first form on the page is always checked instead of the active form.

**Comment by mawtex** [comment]
Thanks for reporting this, Form Builder 1.3.4 has your fix :)
