### ISSUE TITLE
HTML Open Graph meta tags in function not overriding template in v6.6

### ISSUE THREAD

**Issue by tsulli** [Orckestra/C1-CMS-Foundation#648]
**Scenario:**

Template header has generic value for @meta.Facebook.Url in tag:
`<meta property="og:url" id="ogurl" content="@meta.Facebook.Url" />`

Function has more specific page value for @meta.Facebook.Url in tag:
`<meta property="og:url" id="ogurl" content="@meta.Facebook.Url" />`

**Expected:** 
Function meta tag shows in page source, as per [Controlling <head/>Element](https://docs.c1.orckestra.com/Layout/Controlling-HTML-Head)

**Actual:** 
Template meta tag shows in page source. (If I remove the template meta tag, the function meta tag will then appear in it's place.)

This seems to happen with all types of Open Graph meta tags, not just og:url. (For example, also seeing it happen with og:image, og:type, og:description, etc.) The non-Open Graph meta tags with 'name="description"' DO seem to be overriding the template as they should. 

We are using C1 CMS v6.6.6912.30810. I'm aware that this is a bug that was previously fixed in v6.6 per release notes but I'm still seeing this incorrect behavior.

**Comment by mawtex** [comment]
I pushed a fix - can you test is looks good with your case? Fetch dev branc, build and copy over Composite.dll on a running 6.6 should do the trick.

**Comment by tsulli** [comment]
Sorry it took me so long to get back to you, Marcus - it worked perfectly. Thank you!
