### ISSUE TITLE
[improvement] Add ConsoleId as Query-Parameter in UrlActionTokenActionExecutor

### ISSUE THREAD

**Issue by ckeller81** [Orckestra/C1-CMS-Foundation#652]
As our current project requires heavy C1 console customizations, I'm using many custom console pages to add custom functionality to the console. There I was struggling with the usage of the ConsoloeMessageQueueFacade to enqueue eg. new OpenViewMessageQueueItem Messages.

Most of the time, I want to open a new page (using UrlActionToken) on the current console. For this, you always need to know the current ConsoleId. But on a custom page, this is mostly impossible (or did I miss something here?).

The only way to get the consoleId, is to add a own ActionToken including a custom IActionExecutor implementation who adds the consoleId (from FlowControllerServicesContainer/IManagementConsoleMessageService given in the IActionExecutor).

After looking at the C1 source, in the Composite.C1Console.Actions.UrlActionTokenActionExecutor class, the URL is already extended with the current entityToken, so it would be not that much of an effort to add the current consoleId to the URL too. :)

Would it be possible that in a future C1 version, this could be added, or are there any unknown side-effects of such a change?

Thanks and have a great day,
Christoph

**Comment by ckeller81** [comment]
I have a commit ready to solve this, but it seems that I do not have push access to this repo. :)
Is there a possibility to get the push-access-rights?

Thanks in advance,
Christoph

**Comment by mawtex** [comment]
Can you please send a pull request?

**Comment by ckeller81** [comment]
Pull request is done :)

**Comment by mawtex** [comment]
Merged, thanks!
