### ISSUE TITLE
[Bug] Using two HtmlBlob Controls in same DynamicTypeForm gives error

### ISSUE THREAD

**Issue by ckeller81** [Orckestra/C1-CMS-Foundation#654]
Using more than one <HtmlBlob> Element in a DynamicTypeForm gives an alert 'Element "scrollbox" encountered twice'.

In HtmlBlob.ascx, the scrollbox have an id, which is not used anywhere, so I assume that it is save to remove it. Will add a pull request soon.

**Comment by mawtex** [comment]
Thanks!
