### ISSUE TITLE
How to replace a plugin's dynamic data type with a static class?

### ISSUE THREAD

**Issue by ai-fwd** [Orckestra/C1-CMS-Foundation#659]
I'm using a C1 plugin that I dynamically creates a datatype via a DataTypeDescriptor which can be found [here](https://github.com/Orckestra/CMS-Packages/blob/master/Composite.Community.Blog/Composite.Community.Blog.Package/Package/DataTypeDescriptors/Composite.Community.Blog.Entries.xml)

This datatype lives in the generated.dll as a result.

I would like to make a few changes to the generated datatype but i'm unclear on how to go about this. Does anyone know if it is possible and if so, how?

**Comment by mawtex** [comment]
**To make changes to the type:**
Just use the UI to edit the data type as if it were your own, it should be that simple. You find on the type if the Data perspective. 

When you save, the definition is updated along with the generated code, and the generated dll ends up updated.

If you change the type or name of an existing field, you may likely experience existing code that came with the package do not compile and you then also need to update that code.

To move the type from 'UI controlled' to 'code controlled'
You can move the data type from the 'dynamic' realm, to being a pure code based data type, here is a tool for that: https://c1.orckestra.com/Add-ons/All/Composite.Tools.StaticDataTypeCreator - with this you can move the type out of the generated dll and into your own project/assembly.

The path here is typically: Capture the source code (using the linked tool), delete the types, re-introduce them as code types.

**Comment by mawtex** [comment]
> It's not possible to edit any of the attributes of the model via the UI

After the Composite.Community.Blog package is installed, you should see 3 new data types below "Global Datatypes" on the Data perspective, and you should be able to edit those types.

For the "Entries" type (your blog posts), if you want to modify the editing UI for this, you also need to execute the "Edit Form Markup" command on it and get your changes in there. This type has a custom layout, which you edit using this command..

> Deleting the types will also delete the data

True, you should copy all Composite.Community.Blog.*.xml files from the ~/App_Data/Composite/DataStores directory and once your static type is up and running, copy the files back. If you are on SQL Server, do the same, just for the similar named tables.

**Comment by ai-fwd** [comment]
@mawtex for the first comment i'm specifically looking to modify the DataAncestorProvider but based on your answers it looks like i'm going to have to recreate the type and migrate.
