### ISSUE TITLE
Linux / Dotnet Core support??

### ISSUE THREAD

**Issue by mjaperta** [Orckestra/C1-CMS-Foundation#670]
Hi

How hard would it be to get C1 running on dot net core on Linux??

I'm trying to compile it with Mono on Linux, but ending up with missing workflow types...

**Comment by mawtex** [comment]
Hi,

tl;dr: sorry, no. Tons of work.

Currently it's only the full .NET Framework that can run C1, one reason being  the use of Workflow Foundation from .Net v3. C1 is dating back 12 years so there are a few parts of .net that did not make it into mono or .net core.

It is a big project getting on .net core, so I cannot say how fast we will get there, but we will be moving in that direction, incrementally, using .net standard as a path, so we can keep shipping C1.

**Comment by djalfe** [comment]
Is it only Umbraco that has seen the light?
