### ISSUE TITLE
Dynamically generated long URL

### ISSUE THREAD

**Issue by BasithBasheer** [Orckestra/C1-CMS-Foundation#671]
I am facing an issue regarding the dynamically generated URL. I have created a CMS and most of the data are dynamically added global data. All the details are fetching based on the GUID of the data. The issue is when fetching the data the URL becomes longer. For example please check the below URL.

https://www.kfas.com/What-We-Offer/private-sector/training?sid=491a7a60-378e-4bf6-b547-4490bd5d2e1f&iv=1&itemid=54348f8c-0859-4d99-a683-40d3c256c5fd&rd=n#secItems 

The long URL is making issue in the SEO. So, please advise me if there is any way to make the long URL into short URL in the C1 CMS Foundation.

**Comment by burningice2866** [comment]
You can shorten the guids from 36 characters to 22 by Base64  encoding them as described in this article

https://www.codeproject.com/Tips/1236704/Reducing-the-string-Length-of-a-Guid

**Comment by mawtex** [comment]
There are typically two ways URLs can come about:

 - using the automatic link/url feature in C1 - these URLs do not use query strings (URLs with ? in them)
   (for more on this feature see
 - custom code - URLs can look like anything, depending on the custom code.

I don't recognize the URL structure you write as something C1 CMS would generate, so my guess is that the link is created by some custom code.

If the URL is the result of custom code, you need to address that and modify it.

If you do modify it, one direction could be to use the techniques described at https://docs.c1.orckestra.com/Data/Linking-to-Data-Items (see second part and sub pages). But likely doing small tweaks to your custom code will be fastest to do.

If this is not relevant to your situation, please provide more details on how the URL you have is generated / parsed.

**Comment by burningice2866** [comment]
If you're worried about your SEO i would seriously consider using the names of your categories and items as url idenfiers instead of their guid-ids.

So you have something like this instead

https://www.kfas.com/What-We-Offer/private-sector/training/business/mba?iv=1&rd=n#secItems

**Comment by BasithBasheer** [comment]
> You can shorten the guids from 36 characters to 22 by Base64 encoding them as described in this article
> 
> https://www.codeproject.com/Tips/374025/ShortGUID

Thank You

**Comment by BasithBasheer** [comment]
> There are typically two ways URLs can come about:
> 
> * using the automatic link/url feature in C1 - these URLs do not use query strings (URLs with ? in them)
>   (for more on this feature see
> * custom code - URLs can look like anything, depending on the custom code.
> 
> I don't recognize the URL structure you write as something C1 CMS would generate, so my guess is that the link is created by some custom code.
> 
> If the URL is the result of custom code, you need to address that and modify it.
> 
> If you do modify it, one direction could be to use the techniques described at https://docs.c1.orckestra.com/Data/Linking-to-Data-Items (see second part and sub pages). But likely doing small tweaks to your custom code will be fastest to do.
> 
> If this is not relevant to your situation, please provide more details on how the URL you have is generated / parsed.

Thanks.

**Comment by BasithBasheer** [comment]
> If you're worried about your SEO i would seriously consider using the names of your categories and items as url idenfiers instead of their guid-ids.
> 
> So you have something like this instead
> 
> https://www.kfas.com/What-We-Offer/private-sector/training/business/mba?iv=1&rd=n#secItems

okay
