### ISSUE TITLE
PWA Implementation: Service Worker error - Vary Header Contains *

### ISSUE THREAD

**Issue by neberaa** [Orckestra/C1-CMS-Foundation#672]
**Repro:**
1. Create service worker(sw) file, register it in the template layout file.
2. Inside sw file try to cache any page.
3. Use Google Chrome/Firefox and open a console.
3. During  worker's installation browser throws an error `TypeError: Vary header contains *`.
4. Additional send GET request and see Headers -> Vary.

**Actual:**
1. Any page always returns `Vary -> *` even when `Web.config` set `varyByParam` to `Accept-Encoding` or any other.

**Expected:**
1. Vary Header should be flexible and configurable to allow using PWA features and service worker precaching assets and pages.

**Screenshots:**
1. ![img1](https://user-images.githubusercontent.com/20709840/58548861-71d88100-81c7-11e9-9718-328aa6f1058d.jpg)
2. ![img2](https://user-images.githubusercontent.com/20709840/58548862-71d88100-81c7-11e9-8278-e216fd2cb061.jpg)
3. ![img3](https://user-images.githubusercontent.com/20709840/58548863-71d88100-81c7-11e9-9073-0bc296f0596e.jpg)

**Comment by napernik** [comment]
Hi @neberaa

This is the default ASP.NET behavior, which can be disabled by  using `<outputCache omitVaryStar="true" />` attribute:

```
    <caching>
      <outputCache omitVaryStar="true" />
      <outputCacheSettings>
        <outputCacheProfiles>
          <add name="C1Page" duration="60" varyByParam="*" varyByCustom="C1Page" />
        </outputCacheProfiles>
      </outputCacheSettings>
    </caching>

```
With this, the response will have **Vary: Accept-Encoding** as a default value for cached responses.
If you want to change the "Vary" header to a different value, you can use **varyByHeader** attribute:

```
    <caching>
      <outputCache omitVaryStar="true" />
      <outputCacheSettings>
        <outputCacheProfiles>
          <add name="C1Page" duration="60" varyByParam="*" varyByHeader="Accept-Language" varyByCustom="C1Page" />
        </outputCacheProfiles>
      </outputCacheSettings>
    </caching>
```

**Comment by neberaa** [comment]
Thanks Dmitry. It works!
