### ISSUE TITLE
Item locked warning does not consider language (?)

### ISSUE THREAD

**Issue by MarcoDieleman** [Orckestra/C1-CMS-Foundation#673]
We support a multi lingual website and we (and other editors) are getting warnings when trying to open a page. The warning indicates that the page is in use or is being edited, while we're sure it's not. It looks like the warning does not consider the language version of the page. If the page is not closed correctly in Spanish, we get a warning when opening the English version.

**Comment by mawtex** [comment]
Can confirm this is an issue - multiple users editing different language versions of a page or other localized data, will get the "other user editing this" warning.

**Comment by mawtex** [comment]
@MarcoDieleman the issue has been fixed now in our dev branch and is available in the next release. If you are on a 6.6 and would like to apply the fix asap, it is also safe to build composite.dll from this branch and copy over.

**Comment by MarcoDieleman** [comment]
Great! Thank you.
