### ISSUE TITLE
The date field doesnt shows properly in Google chrome

### ISSUE THREAD

**Issue by ferhatraj** [Orckestra/C1-CMS-Foundation#688]
While opening C1 admin panel in Google chrome, the data field doesn't appear in the Data section. Please find the attached screenshot
![Composite-date-error-in-chrome](https://user-images.githubusercontent.com/3403467/66384531-9808fb80-e9c7-11e9-972d-1d4bebff3ea9.png)

**Comment by mawtex** [comment]
Duplicate of issue #666, closing.
