### ISSUE TITLE
Provide a security contact for a critical vulnerability submission

### ISSUE THREAD

**Issue by Frycos** [Orckestra/C1-CMS-Foundation#690]
Hi guys,

I tried to contact your team via email (c1support@ from your website) as well as over Twitter. No response so far. In parallel I did submit an issue at the HackerOne disclosure assistant for this issue but I wanted to give you another possibility for a reaction maybe here over Github. HackerOne did not trigger the first step by now.

Please provide a security contact (maybe with option of encryption if you like).

Thanks.

**Comment by mawtex** [comment]
I don't see your mail to c1support@ make it all the way through to our zendesk :/ Can you please mail marcus.wendt@ instead?

Thanks!
