### ISSUE TITLE
With specific custom IIS cache rule for .jpg, images from CMS always show same image

### ISSUE THREAD

**Issue by mawtex** [Orckestra/C1-CMS-Foundation#698]
Users - with a local modified cache settings in IIS/web.config, upgrading from versions older than 6.3 to 6.3 or later, may experience this behavior:

C1 starts outputting the same image for all image requests. Any request to the website starting with the pattern `/media/{GUID}` does this.

Please note it is not standard in C1 CMS to have specific cache rules, so for this issue to exist, such a rule must have been added manually to IIS/web.config.  

Fix:
Open web.config, and locate the <add extension=".jpg" /> element below:

        <caching>
            <profiles>
                <add extension=".jpg" policy="CacheForTimePeriod" kernelCachePolicy="CacheForTimePeriod" duration="01:00:30" />
            </profiles>
        </caching>

Either remove this cache rule or add the attribute to the <add /> element: `varyByQueryString="true"`

**Comment by mawtex** [comment]
Issue added here for visibility, but this should be considered a "mis-configuration" and the fix is to not make IIS cache files based on path only - if you cache, add varyByQueryString="true"

**Comment by bv-it** [comment]
EN: We have global IIS settings that work well for all sites on different CMS (C1 CMS before 6.3, Umbraco, NopCommerce, etc.). It is necessary to individually remake more than 50 sites on C1 CMS
RU: У нас есть глобальные настройки IIS, которые хорошо работают для всех сайтов на разных CMS (C1 CMS до 6.3, Umbraco, NopCommerce и т. д.). Необходимо индивидуально переделать более 50 сайтов на C1 CMS.

EN: Overriding IIS settings individually for each C1 CMS site will cause inconvenience. Can you give an example of overriding IIS settings at the computer level only for C1 CMS sites? (a rule that will not affect other sites)
RU: Переопределение параметров IIS индивидуально для каждого сайта C1 CMS приведет к неудобствам. Можете ли вы привести пример переопределения параметров IIS на уровне компьютера только для сайтов C1 CMS? (правило, которое не повлияет на другие сайты)

**Comment by mawtex** [comment]
@bv-it did you try the suggested change to web.config above? If you have a specific cache rule for .jpg hard coded for the entire server, then I would expect adding the rule in local web.config is a good fix. Remember having varyByQueryString="true" in the rule's <add/> element.
