### ISSUE TITLE
Splash Screen Resources Not Loading Over HTTPS

### ISSUE THREAD

**Issue by rmzeck** [Orckestra/C1-CMS-Foundation#724]
For the past couple weeks I've been noticing that the admin splash screen hasn't been loading properly. Decided to look into it today, and I found that a handful of resources aren't being loaded for sites using HTTPS. Looking into this a bit further, it seems like this is stemming from the certificate on c1console.composite.net having expired back on the 2nd of this month.

![2020-02-19_102459](https://user-images.githubusercontent.com/19580957/74848302-8a646a80-5305-11ea-87d3-396d428d5913.png)
![2020-02-19_102722](https://user-images.githubusercontent.com/19580957/74848303-8a646a80-5305-11ea-96c4-b51f1dc14aaa.png)
![2020-02-19_103205](https://user-images.githubusercontent.com/19580957/74848304-8a646a80-5305-11ea-81e6-3c4465249260.png)

Thanks

**Comment by dabitbol** [comment]
Hi! We have received the necessary certificate and the issue should resolved today

**Comment by rmzeck** [comment]
thank you!
