### ISSUE TITLE
Usage of JsonConvert.SerializeObject should not rely on default JsonSerializerSettings

### ISSUE THREAD

**Issue by burningice2866** [Orckestra/C1-CMS-Foundation#733]
Method CompositeJsonSerializer.SerializePartial is relying on default JsonSerializerSettings which can be overridden by user code, and its therefor important that all non-solution specific code don't rely on default JsonSerializerSettings but always pass its own explicit settings.

**Comment by napernik** [comment]
PR merged for the good refactoring part
