### ISSUE TITLE
Runtime compilation should be based on DotNetCompilerPlatform

### ISSUE THREAD

**Issue by burningice2866** [Orckestra/C1-CMS-Foundation#735]
Current runtime compilation done by C1 is handled by the legacy CSharpCodeProvider builtin .Net framework. This should be switched so it handled by CSharpCodeProvider shipped with Microsoft.CodeDom.Providers.DotNetCompilerPlatform which is based on Roslyn and supports all the newest C# syntax and features.

Since C1 already ships Microsoft.CodeDom.Providers.DotNetCompilerPlatform as part of the website project this wouldn't introduce any new dependencies.

I can work on a PR if this is something the would be accepted.

**Comment by napernik** [comment]
Yes, if you make a PR, I'll merge it when preparing the next release (expected in 2-3 month).

**Comment by napernik** [comment]
PR merged
