### ISSUE TITLE
[Bug] C1 CMS 6.8 - LogFiles folder NOT re-created automatically

### ISSUE THREAD

**Issue by VolodymyrMuzyka** [Orckestra/C1-CMS-Foundation#739]
Prior to C1 6.8 when this folders get deleted:

\App_Data\Composite\LogFiles 
\App_Data\Composite\Cache 
\App_Data\Composite\ApplicationState

they get re-created automatically with next CMS start...

with C1 6.8 \App_Data\Composite\LogFiles not re-created and throwing an exception.

**Comment by napernik** [comment]
Currently not reproducible
