### ISSUE TITLE
Site loads fine. But C1 admin panel Shows error.

### ISSUE THREAD

**Issue by sandip619007** [Orckestra/C1-CMS-Foundation#749]
Site loads fine. But C1 admin panel Shows error as:

"Depending on your internet connection speed, may take a few moments to load.

Initializing

Shutting down..."

![Issue](https://user-images.githubusercontent.com/66553820/84908715-70c80980-b0d2-11ea-90ba-7c3da0e0692f.jpg)

**Comment by Rogn** [comment]
You should only be seeing that content if the System has not been initialized successfully.
What is the content of the ~/App_Data/Composite/Configuration/SystemInitialized.xml file?

**Comment by napernik** [comment]
It looks like some kind of a javascript error, preventing the page from showing correctly. Can you check it in the Chrome Developer console?

**Comment by sandip619007** [comment]
> You should only be seeing that content if the System has not been initialized successfully.
> What is the content of the ~/App_Data/Composite/Configuration/SystemInitialized.xml file?

Thanks for the response. Here is the content :

﻿<?xml version="1.0" encoding="utf-8"?>
<Root Status="true" />

**Comment by sandip619007** [comment]
> It looks like some kind of a javascript error, preventing the page from showing correctly. Can you check it in the Chrome Developer console?

Thanks for the response. As you suggested, it seems a javascript error. Please see the Chrome developer console screenshot. 
![Git](https://user-images.githubusercontent.com/66553820/85117493-9709b880-b23c-11ea-8b93-80a2d4da0bea.jpg)

**Comment by napernik** [comment]
@sandip619007 I didn't have a good suggestion before, but now I found a likely explanation: IIS isn't serving static files (.css,.js, etc.). The fix would be to install the missing features:

![image](https://user-images.githubusercontent.com/1391705/85748936-b60abd80-b708-11ea-911e-5d1bd97065c6.png)


Seemingly the same issue described here:
https://github.com/Orckestra/BetterRetail/issues/32

**Comment by Mathieu265** [comment]
On my side it was a configuration error. The repo folder need to have some permission setup
![image](https://user-images.githubusercontent.com/6610671/86131928-4142d500-bab4-11ea-90e7-94ec9303dd95.png)

**Comment by sandip619007** [comment]
Hi All,

The above issue was fixed by adding permission for 'Everyone'. Also, the hosting server team by mistake changed the ASP.NET version. Now it loads fine. Thank you all for your support. May this help someone someday. Peace.
