### ISSUE TITLE
[Bug] C1 CMS 6.9: {body}#xD; added to TextArea parameter value in function with TextArea parameter

### ISSUE THREAD

**Issue by VolodymyrMuzyka** [Orckestra/C1-CMS-Foundation#755]
Repro: Insert function with TextArea parameter, add value:

---
^[a-z0-9.-_]{1,55}\@([a-z0-9.]{0,20})nyu.edu$
second line
--

Switch to Source mode - now parameter added with "{body}#xD;"

Example in source: 
<f:param name="Description" value="^[a-z0-9.-_]{1,55}\@([a-z0-9.]{0,20})nyu.edu${body}#xD;&#xA;second line" />

Example in Visual:
---
^[a-z0-9.-_]{1,55}\@([a-z0-9.]{0,20})nyu.edu${body}#xD;
second line
---

**Comment by neexite** [comment]
It happens becouse $& is reserved  replacement pattern for String.replace function
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace

The easiest way to reproduce insert into page content '$&'

**Comment by neexite** [comment]
Another issue
![image](https://user-images.githubusercontent.com/14817424/94686084-f8105480-0332-11eb-9d17-869e6866b7f9.png)

**Comment by neexite** [comment]
3rd test case: insert $$ => $
