### ISSUE TITLE
[Bug] Duplicated Title tag when enabling omitAspNetWebFormsSupport

### ISSUE THREAD

**Issue by ckeller81** [Orckestra/C1-CMS-Foundation#776]
Prerequisite:
- Fresh Composite C1 6.10 installation with Venus template

Reproduction steps:
- Edit composite.config and set omitAspNetWebFormsSupport to true
- restart C1
- Navigate with browser to page '/Blog/2014/06/30/How-to-view-unpublished-and-unsaved-pages' and view HTML source-code

Expected behaviour:
- HTML title-tag exists exactly once and its content is "How to view unpublished and unsaved pages"

Actual behaviour:
- There are two HTML title-tags
- One contains "Blog" as content and the other contains "How to view unpublished and unsaved pages"

It seems that the head-tag-merge is somehow broken, after setting omitAspNetWebFormsSupport to true. When set to false, this reverts and the title tag is merged again.

**Comment by ckeller81** [comment]
Are there any news about this issue (at least a comment or a assignement would be great).

Thanks in advance,
Chris

**Comment by napernik** [comment]
Hi Chris, it seems to be a bug, we will look into it.

**Comment by napernik** [comment]
Fixed, thank you for reporting the issue.
