### ISSUE TITLE
[Error] expired certificate used for package-server URL

### ISSUE THREAD

**Issue by ckeller81** [Orckestra/C1-CMS-Foundation#794]
2 years later after #718, the package-server certificate is again expired.

It is for this package server URL:
https://package.composite.net/C1.asmx

Could you please refresh your HTTPS certificate? :)

Thanks and have a nice day,
Chris

**Comment by napernik** [comment]
Hi Chris

The issue has been resolved, sorry for the inconvenience.

**Comment by ckeller81** [comment]
I have set a reminder in my calendar for March 10th 2023, to send you a reminder issue if needed ;)

**Comment by ckeller81** [comment]
@napernik it's one year later :)
Don't forget to renew the certificate by the end of the 13th.

**Comment by burningice2866** [comment]
😃 

![image](https://user-images.githubusercontent.com/333952/224300387-ce83b006-7757-44d2-8c8f-d9654f9653c0.png)

I can recommend automating it using [Let's Encrypt](https://letsencrypt.org/) and [Certify The Web](https://certifytheweb.com/)

**Comment by burningice2866** [comment]
Due to unfathomable reasons the certificate expired today. Is the C1 CMS Foundation really dead?
