### ISSUE TITLE
v5 user interface looks washed-out on non-IPS displays

### ISSUE THREAD

**Issue by DBailey635** [Orckestra/C1-CMS-Foundation#8]
When viewed on a non-IPS twisted nematic type displays (used in cheap laptops or older TFT flat-screens), the new user interface looks very washed out. There needs to be a bit more contrast between text/icons and the background colour. This could be accomplished with a different, heaver font, icons with lines thicker than 1px, or some more use of colour.

**Comment by mawtex** [comment]
We won't address this - I'd recommend building a custom styles.min.css where contrasts are non-IPS friendly and push this to the site affected.
