### ISSUE TITLE
"Please Upgrade - To Stay Safe" - Question about notification 

### ISSUE THREAD

**Issue by dragana1011** [Orckestra/C1-CMS-Foundation#809]
Hello,

Can anyone help me please?

When I login into a Composite I see this notification

![image](https://user-images.githubusercontent.com/23667906/175885341-e2385260-e003-42e1-b5a5-fc0b7637ff45.png)

Since I have CompositeC1.Core NuGet package 6.11.0 installed  I checked if 6.12 version is available and it is not. 
Can you please make it available so I can update?

Thank you.

Dragana

**Comment by napernik** [comment]
Closing as duplicate  #797
