### ISSUE TITLE
Expired SSL Certificate on https://c1console.composite.net/C1.aspx

### ISSUE THREAD

**Issue by burningice2866** [Orckestra/C1-CMS-Foundation#822]
Expired SSL Certificate on https://c1console.composite.net/C1.aspx

**Comment by ckeller81** [comment]
Thanks @burningice2866 for the report, was about to report the same :)

Would be great if the same solution can be applied as for the package-web-service domain (https://package.composite.net/C1.asmx, Let's encrypt certificate).

Thanks for fixing. :)

**Comment by napernik** [comment]
Closing is it was already been fixed

**Comment by ckeller81** [comment]
@napernik no, the domain c1console.composite.net still uses a exired certificate. The package.composite.net domain have the correct one, right, but https://c1console.composite.net/C1.aspx not.

**Comment by burningice2866** [comment]
![image](https://user-images.githubusercontent.com/333952/230065541-414cd299-94fd-451f-a410-0f588c02b1c4.png)
